### ISSUE TITLE
Unable to load sln that contains a net462 project

### ISSUE THREAD

**Issue by lurium** [dotnet/vscode-csharp#1788]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version:
1.17.1
C# Extension version:
1.12.1
## Steps to reproduce
Load a solution that contains a project with a \<TargetFramework\>net462\</TargetFramework\>

## Expected  behavior
It would load properly

## Workaround
```
mkdir %userprofile%\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\Bin 2>NUL
copy /y %userprofile%\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\Microsoft.CSharp.targets %userprofile%\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\Bin
```

## Actual behavior
```
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Users\darby\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\Bin\Microsoft.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(IElementLocation elementLocation, String resourceName, Object arg0)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.LoadProject(String filePath, String solutionDirectory, String sdksPath, ILogger logger, MSBuildOptions options, ICollection`1 diagnostics, ImmutableArray`1& targetFrameworks)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String filePath, String solutionDirectory, String sdksPath, ILogger logger, MSBuildOptions options, ICollection`1 diagnostics)
   at OmniSharp.MSBuild.MSBuildProjectSystem.LoadProject(String projectFilePath)
```

**Comment by rchande** [comment]
@DustinCampbell any idea what's going on here? Based on the workaround, looks like we're failing to locate the msbuild install?
Note that if I try this in an SDK project I get `"SkipNonexistentTargets" parameter is not supported by the "MSBuild" task.` as an error.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

</Project>

```

**Comment by DustinCampbell** [comment]
Unfortunately, I don't know exactly what's happening. @rchande : try the building my https://github.com/DustinCampbell/omnisharp-roslyn/tree/locate-msbuild and see if it works with that.

**Comment by rchande** [comment]
@DustinCampbell looks like your branch fixes this. Do you have an issue I can dupe this against?

**Comment by DustinCampbell** [comment]
Unfortunately, no. I don't have an issue tracking that specific work.

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If this is still a problem, open a new issue at  https://github.com/OmniSharp/omnisharp-roslyn/issues
