### ISSUE TITLE
Errors/Exception shown in Dev tools console

### ISSUE THREAD

**Issue by jtsom** [dotnet/vscode-csharp#2591]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.101 [/usr/local/share/dotnet/sdk]
  2.1.105 [/usr/local/share/dotnet/sdk]
  2.1.200 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.400 [/usr/local/share/dotnet/sdk]
  2.1.401 [/usr/local/share/dotnet/sdk]
  2.1.402 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
VS Code version: 1.29-insider
C# Extension version:
1.17.0-beta-5
## Steps to reproduce
Launch VS Code Insiders with a .Net Core project

## Expected  behavior
No Errors in Dev tools console

## Actual behavior
Errors in dev tools console:
```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:280 [Extension Host] [ms-vscode.csharp] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[csharp]', provide the URI of a resource or 'null' for any resource. (at e._validateConfigurationAccess (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:388:245))
t.log @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:280
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3281 [ms-vscode.csharp]root_1.root.setInterval is not a function
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3281
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3281 TypeError: root_1.root.setInterval is not a function
	at AsyncAction.requestAsyncId (/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.17.0-beta5/node_modules/rxjs/scheduler/AsyncAction.js:65:28)
	at AsyncAction.schedule (/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.17.0-beta5/node_modules/rxjs/scheduler/AsyncAction.js:60:35)
	at AsyncScheduler.Scheduler.schedule (/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.17.0-beta5/node_modules/rxjs/Scheduler.js:43:53)
	at DebounceTimeSubscriber._next (/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.17.0-beta5/node_modules/rxjs/operators/debounceTime.js:89:62)
	at DebounceTimeSubscriber.Subscriber.next (/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.17.0-beta5/node_modules/rxjs/Subscriber.js:90:18)
	at Subject.next (/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.17.0-beta5/node_modules/rxjs/Subject.js:55:25)
	at EventEmitter.OmniSharpServer.debounceUpdateProjectWithLeadingTrue (/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.17.0-beta5/out/src/omnisharp/server.js:87:45)
	at emitOne (events.js:121:20)
	at EventEmitter.emit (events.js:211:7)
	at OmniSharpServer._fireEvent (/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.17.0-beta5/out/src/omnisharp/server.js:208:24)
	at OmniSharpServer._handleEventPacket (/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.17.0-beta5/out/src/omnisharp/server.js:508:18)
	at OmniSharpServer._onLineReceived (/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.17.0-beta5/out/src/omnisharp/server.js:479:22)
	at emitOne (events.js:116:13)
	at Interface.emit (events.js:211:7)
	at Interface._onLine (readline.js:282:10)
	at Interface._normalWrite (readline.js:424:12)
	at Socket.ondata (readline.js:141:10)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by akshita31** [comment]
@jtsom Thanks for filing the issue.  I am able to reproduce the error with 1.16.2 as well. However the strange thing is that all the logs are showing up well.

**Comment by JoeRobich** [comment]
Cannot reproduce with current release.
