### ISSUE TITLE
Cannot build with C# extension on Windows ARM64

### ISSUE THREAD

**Issue by richlander** [dotnet/vscode-csharp#3005]
## Environment data
`dotnet --info` output:

```console
C:\Users\rlander\app>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011349
 Commit:    535d46237e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\3.0.100-preview5-011349\

Host (useful for support):
  Version: 3.0.0-preview5-27617-04
  Commit:  f28abecf15

.NET Core SDKs installed:
  3.0.100-preview5-011349 [C:\Program Files (x86)\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19216-08 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27617-04 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27617-04 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version:

```console
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:09.080Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT ia32 10.0.16299
```

C# Extension version: 1.19.0

## Steps to reproduce

* Install VS Code, C# extension and .NET Core 3.0 (from master) on Windows ARM64 machine. All the installs (beyond the OS) are x86 32-bit.
* `dotnet new console`
* Open project in VS Code
* build

## Expected  behavior

* Expect the app to build, same as it does with the same product versions on my x64 box

## Actual behavior

The app builds and runs from the CLI ...

```console
C:\Users\rlander\app>dotnet run
Hello World!
```

It does not build inside VS Code using the `build` verb. It wants to restore constantly.

```console
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\rlander\app\app.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\rlander\app\app.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\rlander\app\app.csproj'
[warn]: OmniSharp.MSBuild.ProjectLoader
        The "MSBuild" task failed unexpectedly.
System.MissingMethodException: Method not found: 'Void System.Collections.Generic.HashSet`1..ctor(Int32)'.
   at Microsoft.Build.BackEnd.TaskBuilder.GetUndeclaredProjects(MSBuild msbuildTask)
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\rlander\app\app.csproj'.
c:\Users\rlander\app\app.csproj
C:\Users\rlander\.vscode\extensions\ms-vscode.csharp-1.19.0\.omnisharp\1.32.18\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1636,5): Error: The "MSBuild" task failed unexpectedly.
System.MissingMethodException: Method not found: 'Void System.Collections.Generic.HashSet`1..ctor(Int32)'.
   at Microsoft.Build.BackEnd.TaskBuilder.GetUndeclaredProjects(MSBuild msbuildTask)
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

[info]: OmniSharp.MSBuild.ProjectManager
        Update project: app
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        app: Did not find 'runtime.win-x86.Microsoft.NETCore.DotNetAppHost' in lock file.
```

**Comment by rchande** [comment]
@richlander Can you help me get a machine where I can play around with this?

**Comment by richlander** [comment]
Yes. Will get you one.

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue.
