### ISSUE TITLE
[renderer1] [error] ["Extract: EEXIST: file already exists, mkdir 

### ISSUE THREAD

**Issue by Jaftali** [dotnet/vscode-csharp#4929]
We are a school and would like to use Visual Studio Code together with the Omnisharp extension.

The students' working environment has the following characteristics

- Server-stored home directories
- Active Directory environment
- Samba 4.x is used as Active Directory domain controller
- Students do not have write access to C:.
- Extensions are provided locally as a .vsix
- file Access to the Marketplace is not permitted
- --extensions-dir=H:\vscode\ext is used to redirect the extension directory to the student's server-stored home directory when starting Visual Studio Code.

Unfortunately, students can't install an extension (.vsix). The following error appears:
```
[2021-12-06 11:20:42.962] [renderer1] [error] ["Extract: EEXIST: file already exists, mkdir 'H:\\vscode\\extensions\\.819a7632-05f1-4909-b81c-aaf7c669f02b\\.debugger\\cs'","    at s.extractAtLocation (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:188875)","    at async s.extractUserExtension (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:185594)","    at async q.extract (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:198974)","    at async q.doRun (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:199612)"]
[2021-12-06 11:20:42.988] [renderer1] [error] EEXIST: file already exists, mkdir 'H:\vscode\extensions\.819a7632-05f1-4909-b81c-aaf7c669f02b\.debugger\cs': Extract: EEXIST: file already exists, mkdir 'H:\vscode\extensions\.819a7632-05f1-4909-b81c-aaf7c669f02b\.debugger\cs'
    at s.extractAtLocation (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:188875)
    at async s.extractUserExtension (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:185594)
    at async q.extract (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:198974)
    at async q.doRun (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:199612)
```

This behaviour cannot be easily reproduced in another active directory domain. Does anyone know anything about this error message?

**Comment by gregg-miskelly** [comment]
I don't know anything about that error, but the code in question is part of VS Code rather than this extension. So *maybe* someone in VS Code could help.

**Comment by JoeRobich** [comment]
Closing due to lack of activity.
