### ISSUE TITLE
Taking too much time or not formatting the code

### ISSUE THREAD

**Issue by sanamhub** [dotnet/vscode-csharp#4975]
## Environment data
```
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

VS Code version: 1.63.2
C# Extension version: 1.23.17

## OmniSharp log

```
Starting OmniSharp server at 12/25/2021, 7:25:09 PM
    Target: e:\Projects\dotnet\dotnet-mvc

OmniSharp server started.
    Path: c:\Users\sanam\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\OmniSharp.exe
    PID: 15492

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2022 17.0.32014.148 17.0.0 - "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
            2: StandAlone 17.0.0 - "c:\Users\sanam\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2022 17.0.32014.148 17.0.0 - "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\Projects\dotnet\dotnet-mvc'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'e:\Projects\dotnet\dotnet-mvc'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\Projects\dotnet\dotnet-mvc\MvcMovie.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\Projects\dotnet\dotnet-mvc'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\Projects\dotnet\dotnet-mvc' on host 2344.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\Projects\dotnet\dotnet-mvc\MvcMovie.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'e:\Projects\dotnet\dotnet-mvc\MvcMovie.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'e:\Projects\dotnet\dotnet-mvc\MvcMovie.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MvcMovie
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 25.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
[warn]: OmniSharp.MSBuild.ProjectManager
        The change was reported in e:\Projects\dotnet\dotnet-mvc\obj\Debug\net6.0\MvcMovie.GeneratedMSBuildEditorConfig.editorconfig but it doesn't exist on disk.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\Projects\dotnet\dotnet-mvc\MvcMovie.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\Projects\dotnet\dotnet-mvc\MvcMovie.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'e:\Projects\dotnet\dotnet-mvc\MvcMovie.csproj'.
Received response for /quickinfo but could not find request.

Unhandled Exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The project file could not be loaded. Could not find file 'e:\Projects\dotnet\dotnet-mvc\MvcMovie.csproj'.  e:\Projects\dotnet\dotnet-mvc\MvcMovie.csproj ---> System.IO.FileNotFoundException: Could not find file 'e:\Projects\dotnet\dotnet-mvc\MvcMovie.csproj'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Build.Internal.XmlReaderExtension..ctor(String file, Boolean loadAsReadOnly)
   at Microsoft.Build.Construction.ProjectRootElement.LoadDocument(String fullPath, Boolean preserveFormatting, Boolean loadAsReadOnly)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.ThrowInvalidProjectFile(BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Construction.ProjectRootElement.LoadDocument(String fullPath, Boolean preserveFormatting, Boolean loadAsReadOnly)
   at Microsoft.Build.Construction.ProjectRootElement..ctor(String path, ProjectRootElementCacheBase projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.CreateProjectFromPath(String projectFile, ProjectRootElementCacheBase projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded, Nullable`1 preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.OpenProjectOrSolution(String fullPath, IDictionary`2 globalProperties, String toolsVersion, ProjectRootElementCacheBase projectRootElementCache, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Evaluation.Project.ProjectImpl..ctor(Project owner, String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.AspNetCore.Razor.OmniSharpPlugin.DefaultProjectInstanceEvaluator.Evaluate(ProjectInstance projectInstance) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DefaultProjectInstanceEvaluator.cs:line 73
   at Microsoft.AspNetCore.Razor.OmnisharpPlugin.MSBuildProjectManager.RazorDocumentChanged(RazorFileChangeEventArgs args) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectManager.cs:line 111
   at Microsoft.AspNetCore.Razor.OmniSharpPlugin.MSBuildProjectDocumentChangeDetector.FileSystemWatcher_RazorDocumentEvent(String filePath, ProjectInstance projectInstance, RazorFileChangeKind changeKind) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectDocumentChangeDetector.cs:line 145
   at System.IO.FileSystemWatcher.OnDeleted(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

## Steps to reproduce
1. Open VS Code
2. Open Any Model
3. Change and save

### Screenshot:
![image](https://user-images.githubusercontent.com/31341013/147388459-571383f1-d2d4-4c51-996d-22a6da188d16.png)

## Expected  behavior
Success format and save

## Actual behavior
1. Cannot format and message shown as `Saving 'ModelName.cs': Getting code actions from "C#" (configure).`
2. Editor not allowing to save and close the file

**Comment by JoeRobich** [comment]
The error log shows that MSBuild was unable to locate the project file on disk. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
