### ISSUE TITLE
Extension won't load in WSL

### ISSUE THREAD

**Issue by Zeddicus414** [dotnet/vscode-csharp#5348]
## Environment data
`dotnet --info` output from WSL:
```❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.107
 Commit:    f6ec7508e3

Runtime Environment:
 OS Name:     fedora
 OS Version:  35
 OS Platform: Linux
 RID:         fedora.35-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.107/

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  3.1.421 [/usr/lib64/dotnet/sdk]
  6.0.107 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.27 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

VS Code version: 1.70.2 (user setup)
C# Extension version: 1.25.0

## OmniSharp log
Empty

## C# Log
`[ERROR]: C# Extension failed to get platform information.`

## Log (Remote Extension Host)
```
[2022-08-18 07:24:03.184] [exthost] [error] Activating extension ms-dotnettools.csharp failed due to an error:
[2022-08-18 07:24:03.184] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'isWindows')
	at /root/.vscode-server/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:683605
	at Generator.throw (<anonymous>)
	at a (/root/.vscode-server/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:680954)
```

## Steps to reproduce

1. Reload Window
2. Look at errors in logs

## Expected  behavior
Expected C# extension to load

## Actual behavior
It doesn't load at all.

## Additional context
The `csharp: Report and Issue` command led to this:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/31261142/185396427-dbbb1a45-c967-4234-a380-185a88342821.png">

**Comment by JoeRobich** [comment]
A lot has changed with C# extension since this issue was opened. If you are still having problems, please open a new issue.
