### ISSUE TITLE
The extension crashes on launch

### ISSUE THREAD

**Issue by moalamri** [dotnet/vscode-csharp#5483]
## Issue Description ##
The extension crash immediately when I open a dotnet project. It shows the same behavior when I had .NET 6 as default, it still show the same behavior with .NET 7

## Steps to Reproduce ##
1- Open VS Code on dotnet project
2- Extension crash therefore all `cs` files are marked red with errors
<img width="220" alt="image" src="https://user-images.githubusercontent.com/964077/205490810-c4256567-3e39-4348-a47a-f73a1c889d20.png">

## Expected Behavior ##
Not to crash on launch
## Actual Behavior ##
The extension crashes
### Extension Host log ###
```log
2022-12-04 13:36:37.256 [warning] DiagnosticCollection with name 'csharp' does already exist.
2022-12-04 13:36:37.272 [error] [ms-dotnettools.csharp] provider FAILED
2022-12-04 13:36:37.273 [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Request /v2/getcodeactions cancelled, id: undefined
2022-12-04 13:36:38.357 [error] TypeError: Cannot read properties of null (reading 'replace')
    at Function.file (c:\Users\mohammed\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:64:19966)
    at c:\Users\mohammed\.vscode\extensions\ms-dotnettools.csharp-1.25.2-win32-x64\dist\extension.js:2:747508
    at Generator.next (<anonymous>)
    at c:\Users\mohammed\.vscode\extensions\ms-dotnettools.csharp-1.25.2-win32-x64\dist\extension.js:2:734932
    at new Promise (<anonymous>)
    at r (c:\Users\mohammed\.vscode\extensions\ms-dotnettools.csharp-1.25.2-win32-x64\dist\extension.js:2:734677)
    at c:\Users\mohammed\.vscode\extensions\ms-dotnettools.csharp-1.25.2-win32-x64\dist\extension.js:2:747049
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-04 13:36:45.406 [error] [ms-dotnettools.csharp] provider FAILED
2022-12-04 13:36:45.406 [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Request /v2/getcodeactions cancelled, id: 28
2022-12-04 13:36:48.952 [error] [ms-dotnettools.csharp] provider FAILED
2022-12-04 13:36:48.952 [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Request /v2/getcodeactions cancelled, id: undefined
2022-12-04 13:36:50.832 [error] [ms-dotnettools.csharp] provider FAILED
2022-12-04 13:36:50.832 [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Request /v2/getcodeactions cancelled, id: 60
2022-12-04 13:36:52.712 [error] [ms-dotnettools.csharp] provider FAILED
2022-12-04 13:36:52.712 [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Request /v2/getcodeactions cancelled, id: undefined
```
### OmniSharp log ###
<details>
Starting OmniSharp server at 12/4/2022, 1:36:34 PM
    Target: c:\Users\mohammed\Desktop\EQ\BackEnd\EQ.WebApi.sln

OmniSharp server started with .NET 7.0.100
.
    Path: c:\Users\mohammed\.vscode\extensions\ms-dotnettools.csharp-1.25.2-win32-x64\.omnisharp\1.39.2-net6.0\OmniSharp.dll
    PID: 2200

Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
</details>

### C# log ###
<details>No output</details>

## Environment information ##

**VSCode version**: 1.73.1
**C# Extension**: 1.25.2

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.306 [C:\Program Files\dotnet\sdk]
  6.0.402 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.2|
|git-graph|mhutchie|1.30.0|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.6|
|jiratimetracker|moalamri|0.0.3|
|markdown-shiki|bierner|0.1.1|
|unocss|antfu|0.47.5|
|visual-nuget|fullstackspider|0.2.1|
|vscode-pull-request-github|GitHub|0.54.1|
|vscode-rapidapi-client|RapidAPI|1.8.2|
|vscode-yaml|redhat|1.10.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.29|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
