### ISSUE TITLE
New LSP-powered version does not activate when `csharp.inlayHints.*` settings are present in a VSCode profile

### ISSUE THREAD

**Issue by mareklinka** [dotnet/vscode-csharp#5714]
## Environment data
`dotnet --info` output: SDK 7.0.302
VS Code version: 1.78.2 (user setup)
C# Extension version: 2.0.206 (pre-release)

The Extension cannot be activated when installed into a non-default profile:
```
2023-06-07 08:08:42.744 [error] Activating extension ms-dotnettools.csharp failed due to an error:
2023-06-07 08:08:42.744 [error] TypeError: Cannot read properties of undefined (reading 'scope')
    at z.Hb (vscode-file://vscode-app/c:/Users/Marek/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2266:73376)
    at async Promise.all (index 0)
    at async Object.q [as settled] (vscode-file://vscode-app/c:/Users/Marek/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:97:21381)
    at async z.updateValue (vscode-file://vscode-app/c:/Users/Marek/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2266:61461)
```

When I switch my active profile to `Default`, the extension works correctly.

**Comment by mareklinka** [comment]
After further investigation, it seems that this only happens when I try to use the extension on a profile that existed before the pre-release version was released.

This led me to review the VSCode settings stored in the affected profile. After removing all the `csharp.*` and `omnisharp.*` settings form the JSON file, the extension loaded correctly in the profile as well.

So I delved further, and I think the culprit is these settings: `csharp.inlayHints.*`. I had a whole bunch of them set up. When the new extension loads, it seems to attempt to migrate these old settings to a new name `dotnet.inlayHints.*`. Unfortunately, the process seems to crash after migrating exactly 1 setting from the namespace, which causes the extension to not load properly.

After I migrated all the old settings (by repeatedly reloading the VSCode window), I ended up with:

![image](https://github.com/dotnet/vscode-csharp/assets/7479226/19ac0bd2-806d-44b1-9f85-9ad1c832c6d3)

At this point, the extension loaded correctly on first try.

**Comment by Cosifne** [comment]
Tried to repro this locally and it happens when executing
https://github.com/dotnet/vscode-csharp/blob/ea41fa6d43349a4bd1404f4d8e3d68ee77abea32/src/shared/MigrateOptions.ts#L55
(remove the old settings from the options)

I see the old configuration is removed. But it throws an exception and interrupts the start-up of the extension.
It feels like either a misuse of the vs code API on our side/bug in vscode.

**Comment by sinanaltaii** [comment]
I hope his get solved soon :)

**Comment by Cosifne** [comment]
This turns out to be a VSCode bug, and they fixed it in https://github.com/microsoft/vscode/pull/186975
