### ISSUE TITLE
Failure to start a language server connection in a remote

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5742]
C# Extension Version:v2.0.100-beta.g98603998e1
C# Dev Kit Extension Version:v0.0.774-alpha

Steps to reproduce:

1. Launch WSL (I'm using Ubuntu 22 LTS with .NET 7 installed)
2. mkdir 'projects'
3. cd 'projects'
4. `dotnet new console -o c2`
5. cd `c2`
6. `code .`

Launches vs-server, then launches a VS Code instance
Install extensions in that instance and reload.
Logs attached from that instance

ERROR:
Dotnet version: 7.0.102

[Error - 12:07:30 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Cannot find language server in path '/home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/.roslyn/Microsoft.CodeAnalysis.LanguageServer''
    at C.<anonymous> (/home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:964333)
    at Generator.next (<anonymous>)
    at /home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:959975
    at new Promise (<anonymous>)
    at r (/home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:959720)
    at C.startServer (/home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:964134)
    at C.<anonymous> (/home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:961721)
    at Generator.next (<anonymous>)
    at /home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:959975
    at new Promise (<anonymous>)
    at r (/home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:959720)
    at /home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:961669
    at S.createMessageTransports (/home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:1906393)
    at S.createConnection (/home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:1748851)
    at S.start (/home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:1739915)
    at C.<anonymous> (/home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:962139)
    at Generator.next (<anonymous>)
    at s (/home/timheuer/.vscode-server/extensions/ms-dotnettools.csharp-2.0.100-beta.g98603998e1/dist/extension.js:2:959777)

**Comment by liciniomendes** [comment]
Happened to me on `MacOS` with `tmux` 3.3a_2. 

ProductName:		macOS
ProductVersion:		13.4.1
BuildVersion:		22F82

After running `code .` outside `tmux` everything worked. Repeating inside `tmux` was working now.

**Comment by aradalvand** [comment]
Same here; when is this planned to get fixed?

**Comment by pvyadav** [comment]
Same here.

**Comment by JColitti** [comment]
I'm having the same issue when trying to install the C# extension. Reinstalling VSCode didn't work. Is there a fix yet?

**Comment by dibarbet** [comment]
> Same here.
> 
> Error! .NET Acquisition Failed: Installation failed: Error: Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ;

This is an issue on the .net acquisition side (tracking https://github.com/dotnet/vscode-dotnet-runtime/issues/845).
You can likely workaround this by manually pointing it to the installed .net 7 runtime, see https://github.com/dotnet/vscode-dotnet-runtime/issues/845

**Comment by dibarbet** [comment]
> I'm having the same issue when trying to install the C# extension. Reinstalling VSCode didn't work. Is there a fix yet?

To anyone hitting this, please include the logs from the C# output window.  Should help us determine if you're encountering a project load issue or one related to loading on a remote.

**Comment by aradalvand** [comment]
> I'm having the same issue when trying to install the C# extension. Reinstalling VSCode didn't work. Is there a fix yet?

Downgrade the extension version to 1.x
That's what I did and it's currently working, I'll have to stay on that version until this is fixed.

**Comment by mohamedhamdan2002** [comment]
me to , anyone can help me to solve this problem

**Comment by bangbaew** [comment]
Same here on docker image `mcr.microsoft.com/dotnet/sdk:8.0-preview`
C# extension version 1.26.0 works fine even on alpine image.

**Comment by wwindux** [comment]
Same here.

On Linux, I got this:

```Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.```

After a downgrade from ```v2.5.30``` to ```v1.26.0``` , the issue cleared.

**Comment by zaballa12** [comment]
resolveu só com a v1.26.0, sera qual é o problema?

**Comment by dibarbet** [comment]
We've made a number of changes around dotnet resolution and extension management since this issue was filed.  The 2.x version of the extension should be working in remote scenarios.  If you're still having problems, please
1.  Set `dotnet.server.trace` to `Trace`
2.  Reproduce the issue, and save the C# output window logs
3.  File a new issue with those C# output window logs attached.

Thanks!
