### ISSUE TITLE
C# prerelease generates error and never activates

### ISSUE THREAD

**Issue by upCASE** [dotnet/vscode-csharp#5828]
Hi!
I wanted to try the new LSP based extension, but it never activated. Apparently it doesn't work at all, since I can't even use the "report an issue" command.  I tried activating Omnisharp to get the old behaviour with the new extension, but this didn't work either, the error is the same. I tried deactivating other extension, but nothing seems to influence this. Switching back to the release version for now.

The extension host give me the following error messages below:

```
2023-06-19 08:54:13.889 [error] Activating extension ms-dotnettools.csharp failed due to an error:
2023-06-19 08:54:13.889 [error] TypeError: Cannot read properties of undefined (reading 'scope')
    at z.Hb (vscode-file://vscode-app/c:/Users/xxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2269:74144)
    at async Promise.all (index 0)
    at async Object.q [as settled] (vscode-file://vscode-app/c:/Users/xxxxxxAppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:97:21518)
    at async z.updateValue (vscode-file://vscode-app/c:/Users/xxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2269:62177)
2023-06-19 08:54:15.386 [info] Eager extensions activated
```

## Environment data
`dotnet --info` output:
```
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

VS Code version:
1.79.2
C# Extension version:
v2.0.212

## OmniSharp log
 not present as the extension doesn't start

## Steps to reproduce
 Install prerelease extension, open Workspace that used to work before.

## Expected  behavior
Expected to get Intellisense as usual.

## Actual behavior
Nothing, the extension didn't start.

**Comment by dibarbet** [comment]
Now that's an inscrutable error!  Would you mind trying a couple things for me?
1.  Open the extensions folder (can use the below command), close VSCode, delete any ms-dotnettools.... folders you see there, re-open and re-install the prerelease extension?  We've had some issues with the wrong platform being downloaded by the marketplace.
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/126c13c7-d182-4865-be7b-cf316509f1c8)

1.  If you have any custom C# extension settings in your user settings or repo settings, could you try clearing them and restarting?  This is one place that I can think of that uses a 'scope'.  If this works, please send me the previous settings.
2.  If you have any custom themes / theme settings, could you try clearing them and restarting?  Themes also do have scopes, so thinking it could be related.  And same as above, if this works, send me what the previous settings were.

**Comment by upCASE** [comment]
Hi!
Sure thing, glad I can help as I would love to see LSP support working for me :-D

1. Done - didn't change a thing.
2. As I was lazy, I simply deleted all settings -> it worked. Not really sure what caused this.
2a. I reset the settings: Not working as expected.
2b. I changed to the default profile (had another set previously), reinstalled the C# extension and apparently it works!
3. No need for that.

In short: Seems to be the settings. But I'm not really sure if it was something in connection with my profile, or the settings themself... Anyway I'll attach the settings plus the profile I exported before switching to default. Maybe this helps and you can spot what went wrong. I suppose that might be a showstopper for others as well when switching to the new version.

Works for me now and I really like it so far. Nice work!
I would really love to see the DevKit features for TestExplorer under a free license, but I can manage ;-)
[settings_and_profile.zip](https://github.com/dotnet/vscode-csharp/files/11814184/settings_and_profile.zip)

**Comment by dibarbet** [comment]
Thanks - with your profile I can repro the same error.  Investigating!

**Comment by dibarbet** [comment]
Interestingly, I hit the same error when I load your profile, but if I then run the reload window command, the issue seems to go away and never come back.  Does that work for you as well?

**Comment by upCASE** [comment]
Hi!
Glad I could help and that I'm not seeing or chasing ghosts :-D

I tried importing my old profile again and had the same issue. After running ">Developer: Reload Window" the extension activated and the issue is gone!

On a note: VS Code installed the latest prerelease version prior to trying this  (v2.0.238), so the bug is in this release as well.

Thanks for investigating this and I hope this helps you to triage the bug for future releases.
Keep up the great work, I really enjoy the new extension so far (apart from some smaller quirks, but might be related to my setup). I'll leave this open in case you want me to try something else. From my side, feel free to close this issue, as it works for me now.

**Comment by dibarbet** [comment]
I'll leave this open - there's definitely a bug somewhere here during the import.  But since its working for you now and its not the easiest one to debug I'm going to move it down on my list to take care of some other high priority issues.  If it stops working again and a reload doesn't help, let me know.
