### ISSUE TITLE
System.AggregateException: Project system data flow 'Source: 50160389' closed because of an exception

### ISSUE THREAD

**Issue by mamamiawhatacode** [dotnet/vscode-csharp#5831]
=====================
6/19/2023 1:09:37 PM
LimitedFunctionality
System.AggregateException: Project system data flow 'Source: 50160389' closed because of an exception.
missingBuildCount >= 0 (missingBuildCount >= 0)
---> (Inner Exception #0) Microsoft.Assumes+InternalErrorException: missingBuildCount >= 0
   at Microsoft.Assumes.Fail(String message)
   at Microsoft.Assumes.True(Boolean condition, String message)
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.<>c__DisplayClass5_0.<TryUpdate>g__PopulateMissingBuildData|5(<>c__DisplayClass5_1&)
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.<>c__DisplayClass5_0.<TryUpdate>g__ComposeItemUpdates|2()
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.<>c__DisplayClass5_0.<TryUpdate>g__ProcessAddsAndUpdates|0()
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.TryUpdate(IProjectChangeDescription evaluationProjectChange, IProjectChangeDescription buildProjectChange, String projectFullPath, Nullable`1& dependencies)
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencySubscriber.Source.<LinkExternalInput>g__Transform|6_1(IProjectSubscriptionUpdate update)
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Derive[T,TOut](IProjectVersionedValue`1 projectVersionedValue, Func`2 transform)
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencySubscriber.Source.<LinkExternalInput>b__6_0(IProjectVersionedValue`1 u)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================

And all project start looking red

**Comment by mamamiawhatacode** [comment]
Appearing after project starts with dotnet run or 'Run without debugging'

**Comment by dibarbet** [comment]
Thanks.  This appears to be an issue on the C# devkit side.  Closing this issue in favor of https://github.com/microsoft/vscode-dotnettools/issues/184, please track it there.
