### ISSUE TITLE
2.0.251: Cannot find language server in path '[...]Microsoft.CodeAnalysis.LanguageServer'

### ISSUE THREAD

**Issue by artyomszasa** [dotnet/vscode-csharp#5937]
## Environment data
`dotnet --info` output: [dotnet-info.txt](https://github.com/dotnet/vscode-csharp/files/12099156/dotnet-info.txt)
VS Code version: 1.80.1
C# Extension version: 2.0.251

## OmniSharp log
Only "C#" log appears:
```
[Error - 20:45:35] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Cannot find language server in path '/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/.roslyn/Microsoft.CodeAnalysis.LanguageServer'
	at R (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1022392)
	at P.<anonymous> (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1018155)
	at Generator.next (<anonymous>)
	at /home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1012904
	at new Promise (<anonymous>)
	at r (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1012649)
	at P.startServer (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1018072)
	at P.<anonymous> (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1014088)
	at Generator.next (<anonymous>)
	at /home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1012904
	at new Promise (<anonymous>)
	at r (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1012649)
	at /home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1014036
	at s.createMessageTransports (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:2019964)
	at s.createConnection (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1860026)
	at s.start (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1850541)
	at P.start (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1014853)
	at /home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1026692
	at Generator.next (<anonymous>)
	at /home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1012904
	at new Promise (<anonymous>)
	at r (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1012649)
	at t.activateRoslynLanguageServer (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1023368)
	at /home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1037116
	at Generator.next (<anonymous>)
	at s (/home/artyom/.vscode/extensions/ms-dotnettools.csharp-2.0.251/dist/extension.js:2:1032715)
```

## Steps to reproduce

1. Open any C# solution is VS Code

## Expected  behavior
C# language server is started.

## Actual behavior
C# language server not found.

## Additional context
OS: Ubuntu 22.04

**Comment by dibarbet** [comment]
We've had some trouble with our release script and ended up releasing only a partially working version.  For now, please downgrade to the previous prerelease version.  We should have a fixed version up in a couple hours as well.

Unfortunately the vscode marketplace does not allow us to delete specific versions of the extension.

**Comment by Matteeh** [comment]
> We've had some trouble with our release script and ended up releasing only a partially working version. For now, please downgrade to the previous prerelease version. We should have a fixed version up in a couple hours as well.

Thanks! 2.0.238 Worked for me on Ubuntu 22.04

**Comment by incomingstick** [comment]
> > We've had some trouble with our release script and ended up releasing only a partially working version. For now, please downgrade to the previous prerelease version. We should have a fixed version up in a couple hours as well.
> 
> Thanks! 2.0.238 Worked for me on Ubuntu 22.04

2.0.248 also works on Arch Linux with 7.0.109.

Note to anyone happening here, 2.0.249 will also be broken due to https://github.com/dotnet/vscode-dotnet-runtime/issues/1007

**Comment by jasonmalinowski** [comment]
We just uploaded 2.0.283 which should have the fix for the various Linux issues.
