### ISSUE TITLE
connection to server is erroring

### ISSUE THREAD

**Issue by Neon-Cube** [dotnet/vscode-csharp#5989]
Type: <b>Bug</b>
### Steps to reproduce:
1. Open any tModLoader project
2. Hover over any part of the code

### Results:
```
[Error - 10:00:32 PM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 10:00:32 PM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 10:00:32 PM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 10:00:32 PM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 10:00:34 PM] Stopping server timed out
[Error - 10:00:34 PM] Stopping server failed
Error: Stopping the server timed out
	at /home/neoncube/.vscode/extensions/ms-dotnettools.csharp-2.0.312/dist/extension.js:2:2236900
[Error - 10:00:34 PM] Stopping server failed
Error: Stopping the server timed out
	at /home/neoncube/.vscode/extensions/ms-dotnettools.csharp-2.0.312/dist/extension.js:2:2236900
[Error - 10:00:34 PM] Stopping server failed
Error: Stopping the server timed out
	at /home/neoncube/.vscode/extensions/ms-dotnettools.csharp-2.0.312/dist/extension.js:2:2236900
[Error - 10:00:34 PM] Stopping server failed
Error: Stopping the server timed out
	at /home/neoncube/.vscode/extensions/ms-dotnettools.csharp-2.0.312/dist/extension.js:2:2236900
```

Extension version: 2.0.312
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:41:52.615Z)
OS version: Linux x64 6.2.6-76060206-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3299)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.49GB (8.31GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2111c801-069c-42bd-b011-46e56007b987|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
vscrpc:30673769
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076
cmakestatusbarv2:30779594

```

</details>

**Comment by dibarbet** [comment]
> The C# output is still stuck in

That's fine - it means its running correctly - I need to add a log item here that indicates it is started because the current log is pretty misleading.

**Comment by dibarbet** [comment]
> But Intellicode supposedly works, and highlighting is correct.

If this is the case, I'm going to go ahead and close this issue.  Absolutely feel free to re-open this if you encounter the same problem again.

**Comment by beta1scat** [comment]
Hello, I also encountered this problem. My configurationis:

VS Code version: 
```
Version: 1.81.0
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:36:11.334Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-78-generic
```

Extension version: 
```
ms-dotnettools.csdevkit@0.3.21
ms-dotnettools.csharp@2.0.320
ms-dotnettools.vscode-dotnet-runtime@1.6.0
ms-dotnettools.vscodeintellicode-csharp@0.1.26
```
The specific situation is I have already install dotnet 6.0 on my Ubuntu 20.04 and also set environment variable. But when I open the vscode, it will help me download dotnet 7.0.9. I find a solution on website is add below code to VsCode user setting.json.
```
"dotnetAcquisitionExtension.existingDotnetPath": [
    {
        "extensionId": "ms-dotnettools.csharp",
        "path": "/usr/share/dotnet/dotnet"
    },
    {
        "extensionId": "ms-dotnettools.csdevkit",
        "path": "/usr/share/dotnet/dotnet"
    }
],
```
After add above code, it doesn't download dotnet 7.0.9, but found another error:
```
Dotnet path: /usr/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
[Error - 1:25:24 PM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 1:25:24 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at s.shutdown (/home/niu/.vscode/extensions/ms-dotnettools.csharp-2.0.320-linux-x64/dist/extension.js:2:2237784)
	at s.stop (/home/niu/.vscode/extensions/ms-dotnettools.csharp-2.0.320-linux-x64/dist/extension.js:2:2237365)
	at s.stop (/home/niu/.vscode/extensions/ms-dotnettools.csharp-2.0.320-linux-x64/dist/extension.js:2:2400537)
	at s.handleConnectionError (/home/niu/.vscode/extensions/ms-dotnettools.csharp-2.0.320-linux-x64/dist/extension.js:2:2243872)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Error - 1:25:24 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 1:25:24 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Info  - 1:25:24 PM] Connection to server got closed. Server will restart.
true
Dotnet path: /usr/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
You must install or update .NET to run this application.

App: /home/niu/.vscode/extensions/ms-dotnettools.csharp-2.0.320-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0-preview.7.22362.8' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  6.0.20 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0-preview.7.22362.8&arch=x64&rid=ubuntu.20.04-x64
You must install or update .NET to run this application.

App: /home/niu/.vscode/extensions/ms-dotnettools.csharp-2.0.320-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0-preview.7.22362.8' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  6.0.20 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0-preview.7.22362.8&arch=x64&rid=ubuntu.20.04-x64
[Error - 1:25:25 PM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 1:25:25 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 1:25:25 PM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 1:25:25 PM] Connection to server got closed. Server will restart.
true
Dotnet path: /usr/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
You must install or update .NET to run this application.

App: /home/niu/.vscode/extensions/ms-dotnettools.csharp-2.0.320-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0-preview.7.22362.8' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  6.0.20 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0-preview.7.22362.8&arch=x64&rid=ubuntu.20.04-x64
[Error - 1:25:25 PM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 1:25:25 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 1:25:25 PM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 1:25:25 PM] Connection to server got closed. Server will restart.
true
Dotnet path: /usr/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
You must install or update .NET to run this application.

App: /home/niu/.vscode/extensions/ms-dotnettools.csharp-2.0.320-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0-preview.7.22362.8' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  6.0.20 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0-preview.7.22362.8&arch=x64&rid=ubuntu.20.04-x64
[Error - 1:25:25 PM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 1:25:25 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 1:25:25 PM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 1:25:25 PM] Connection to server got closed. Server will restart.
true
Dotnet path: /usr/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
You must install or update .NET to run this application.

App: /home/niu/.vscode/extensions/ms-dotnettools.csharp-2.0.320-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0-preview.7.22362.8' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  6.0.20 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0-preview.7.22362.8&arch=x64&rid=ubuntu.20.04-x64
[Error - 1:25:25 PM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 1:25:25 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 1:25:25 PM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 1:25:25 PM] The Microsoft.CodeAnalysis.LanguageServer server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by dibarbet** [comment]
@beta1scat the server requires a .net 7 runtime to start - from your dotnet info it looks like you only have a .net 6 runtime from the .net6 SDK.  

You should be able to resolve it by installing the .net7 runtime (or sdk).  Note that you do not need to use .net7 for your project, it just has to exist on the machine in `/usr/share/dotnet/dotnet` so that the server can find and use the .net7 runtime to start itself.

**Comment by domoAA** [comment]
@Neon-Cube Currently running into the same issue while working with tMod, did you solve said issue?

**Comment by Neon-Cube** [comment]
@domoAA Seems like the only working solution as of yet is either switching to an actual IDE (at least until C# Dev Kit reaches an actual release) or working with only the C# extension.

**Comment by beta1scat** [comment]
@dibarbet Thanks for your reply, I have already install dotnet 7.0, but when I open vscode, it also `Dowloading the .NET Runtime`. Should I set up something else?

```
Downloading the .NET Runtime.
Downloading .NET version(s) 7.0.9 ........................................................................................................................... Error!
Failed to download .NET 7.0.9:
.NET installation timed out.

 Error!
.NET Acquisition Failed: Installation failed: Error: .NET installation timed out.

 Error!
.NET Acquisition Failed: Installation failed: Error: .NET installation timed out.

```

Dotnet info is: 
```
(base) ➜ /usr/share/dotnet ./dotnet --info     
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.306/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  6.0.412 [/usr/share/dotnet/sdk]
  7.0.306 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/niu/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by Neon-Cube** [comment]
@beta1scat The .NET acquisition tool is known to be especially buggy on Linux. Try setting the dotnet path in the settings.

**Comment by dibarbet** [comment]
> Thanks for your reply, I have already install dotnet 7.0, but when I open vscode, it also `Dowloading the .NET Runtime`. Should I set up something else?

To confirm, do you still have the `dotnetAcquisitionExtension.existingDotnetPath` in your settings pointing to `/usr/share/dotnet`?

**Comment by beta1scat** [comment]
> > Thanks for your reply, I have already install dotnet 7.0, but when I open vscode, it also `Dowloading the .NET Runtime`. Should I set up something else?
> 
> To confirm, do you still have the `dotnetAcquisitionExtension.existingDotnetPath` in your settings pointing to `/usr/share/dotnet`?

Thanks for your reply, it solved my problem, but I got another error in `C#` extension `OUTPUT`:
```
Dotnet path: /usr/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...
[Error - 3:47:24 PM] [LanguageServerHost]System.InvalidOperationException: Was not able to get hello world response from remote - line 39
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.HelloWorld.RemoteHelloWorldProvider.SayHelloToRemoteServerAsync(CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/RemoteHelloWorldProvider.cs:line 39
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.ServiceBrokerFactory.CreateAndConnectAsync(String brokeredServicePipeName) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/ServiceBrokerFactory.cs:line 82
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
```
And when I restart vscode, it stuck at Starting server:
```
Dotnet path: /usr/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...
```

**Comment by Neon-Cube** [comment]
@beta1scat,

As @dibarbet said,
> That's fine - it means its running correctly - I need to add a log item here that indicates it is started because the current log is pretty misleading.

**Comment by enderesting** [comment]
I've been having a similar problem as @beta1scat... I have the newest version .net 7.0.306 downloaded, but perhaps it's looking in the wrong location?

```
2023-08-30 20:31:38.137 [info] No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

2023-08-30 20:31:38.151 [info] Additional information of .NET SDKs for diagnostic.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /snap/dotnet-sdk/216/sdk/7.0.306/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.306 [/snap/dotnet-sdk/216/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.9 [/snap/dotnet-sdk/216/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.9 [/snap/dotnet-sdk/216/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

2023-08-30 20:31:44.201 [info] Project system initialization finished. 0 project(s) are loaded, and 5 failed to load.
```

The output:
```
Using dotnet configured on PATH
Dotnet path: /usr/bin/snap
Activating C# + C# Dev Kit + C# IntelliCode...
[Error - 8:38:08 PM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 8:38:08 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at s.shutdown (/home/mimi/.vscode/extensions/ms-dotnettools.csharp-2.0.436-linux-x64/dist/extension.js:2:2252253)
	at s.stop (/home/mimi/.vscode/extensions/ms-dotnettools.csharp-2.0.436-linux-x64/dist/extension.js:2:2251834)
	at s.stop (/home/mimi/.vscode/extensions/ms-dotnettools.csharp-2.0.436-linux-x64/dist/extension.js:2:2415006)
	at s.handleConnectionError (/home/mimi/.vscode/extensions/ms-dotnettools.csharp-2.0.436-linux-x64/dist/extension.js:2:2258341)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Error - 8:38:08 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 8:38:08 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Info  - 8:38:08 PM] Connection to server got closed. Server will restart.
true
You must install .NET to run this application.

App: /home/mimi/.vscode/extensions/ms-dotnettools.csharp-2.0.436-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer
Architecture: x64
App host version: 7.0.0-preview.7.22362.8
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.22.04-x64&apphost_version=7.0.0-preview.7.22362.8
```
...And it repeats several times. Notably the Dotnet path `/usr/bin/snap` doesn't match any of my paths that I've set up and doesn't have a dotnet version when i navigated there and checked with? I've been trying to change the path by fiddling with it in settings, but nothing comes about...

@Neon-Cube  mentioned setting the dotnet path in the settings, may I inquire which field that is specifically?? Here are my settings now:
```
{
    "omnisharp.monoPath": "/usr/bin/mono",
    "omnisharp.sdkIncludePrereleases": false,
    "omnisharp.sdkPath": "/snap/dotnet-sdk/216/sdk/7.0.306",
    "omnisharp.useModernNet": false,
    "dotnet.server.useOmnisharp": true,
    "omnisharp.dotNetCliPaths": [
        "/snap/bin/dotnet"
    ],
    "dotnet.defaultSolution": "/snap/bin/",
    "dotnet.unitTestDebuggingOptions": {

    },
    "dotnetAcquisitionExtension.existingDotnetPath": [
        "/snap/bin/dotnet"
    ]
}
```
Now I did check that snap/root has the correct version which is why I set it so. I'm a bit of a newbie so I do apologize if I mixed up any of the paths ^_^;

**Comment by bobombolo** [comment]
I have this problem too and i have both .net 6 and 7 installed

**Comment by Neon-Cube** [comment]
@enderesting 
> @Neon-Cube mentioned setting the dotnet path in the settings, may I inquire which field that is specifically??

In the troubleshooting section of the plugin's details tab, there's an explanation, and I quote:

### I already have a .NET Runtime or SDK installed, and I want to use it
Try adding the requesting extension to the `dotnetAcquisitionExtension.existingDotnetPath` setting in your vscode.json settings file. You can read more about using external installations in our documentation, but here's an example of how to tell the C# extension to use your existing .NET installation:
```json
    "dotnetAcquisitionExtension.existingDotnetPath": [
        {
            "extensionId": "ms-dotnettools.csharp",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        }
    ]
```
For C# Dev Kit you would use the same thing, but with the extension ID `ms-dotnettools.csdevkit`. Other extensions, like the MAUI and Unity extensions, will have their own extension IDs that you can find in the extension pane by right-clicking on them and choosing 'Copy Extension ID'.

NOTE: You'll need to make a new item in the settings array for each extension that uses this extension to acquire .NET.

**Comment by greenhand0403** [comment]
I meet the same problem.
```
dotnet --list-sdks
6.0.413 [/usr/local/share/dotnet/sdk]
7.0.304 [/usr/local/share/dotnet/sdk]
```
```
"dotnetAcquisitionExtension.existingDotnetPath": [
        {
            "extensionId": "ms-dotnettools.csharp",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId": "ms-dotnettools.csdevkit",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId":"ms-dotnettools.vscodeintellicode-csharp",
            "path":"/usr/local/share/dotnet/dotnet"
        }
    ]
```
I can't fix it

**Comment by fyodore82** [comment]
As a suggestion. 
Try to increase Dotnet > Server Start Timeout. 
Default is 30000 ms if I understand correctly

![image](https://github.com/dotnet/vscode-csharp/assets/29746153/1746e77f-c72a-4765-a6c3-d39a6f6c464b)
