### ISSUE TITLE
Update Breaks Unity IntelliSense

### ISSUE THREAD

**Issue by LexGear** [dotnet/vscode-csharp#6014]
After updating to 2.0.3, VS Code no longer connects to Unity. Auto complete no longer works and VS is not able to read code.

Reverting back to latest version 1 installation fixes this issue.

Before reverting, I did try the latest version of Unity and .NET as well as the typical restarting all software and computer.

**Comment by timheuer** [comment]
https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/

**Comment by LexGear** [comment]
> https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/

That's cool. I'll make a mental note of that. But if you look at the one review that extension has, the guy there is complaining about the exact same thing, so my guess is the C# extension breaks that too.

**Comment by OneManMonkeySquad** [comment]
Trying the new extension, I get no syntax highlighting or completions.

```
Dotnet path: c:\Users\Admin\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\dotnet.exe
Activating C# + C# Dev Kit...
info: LanguageServerHost[0]
      Starting server...
[Error - 1:53:32 PM] [LanguageServerHost]System.InvalidOperationException: Was not able to get hello world response from remote - line 39
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.HelloWorld.RemoteHelloWorldProvider.SayHelloToRemoteServerAsync(CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/RemoteHelloWorldProvider.cs:line 39
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.ServiceBrokerFactory.CreateAndConnectAsync(String brokeredServicePipeName) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/ServiceBrokerFactory.cs:line 82
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
```

Unity "Visual Studio Editor" 2.0.20 package is installed, "Visual Studio Code [1.81.0]" is enabled in the preferences.

**Comment by stanica** [comment]
Latest version is still broken. No Intellisense at all with Unity

**Comment by LexGear** [comment]
> Latest version is still broken. No Intellisense at all with Unity. Older versions also don't work

I cannot believe this still isn't fixed. Yeah stanica, just downgrade to the latest version one build and leave it there.

**Comment by mikadumont** [comment]
This should be working see these instructions for setting up Unity with VS Code: https://code.visualstudio.com/docs/other/unity. If you're still experiencing this, feel free to file a new issue.
