### ISSUE TITLE
MSBuild failing to be discovered on MacOS

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/vscode-csharp#6063]
_Originally posted by @Akronae in https://github.com/dotnet/vscode-csharp/issues/6052#issuecomment-1666957403_

```
Dotnet path: /Users/alex/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.9/dotnet
Activating C# standalone...
info: LanguageServerHost[0]
      Starting server...
No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[Error - 9:46:18 PM] [LanguageServerHost]System.InvalidOperationException: Failed to find an appropriate version of .NET Core MSBuild. Call to hostfxr_resolve_sdk2 failed. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.TryEnsureMSBuildLoadedAsync(String workingDirectory) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 119
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 79
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
```

dotnet --info:
```
.NET SDK:
 Version:   7.0.305
 Commit:    98e1b6c381

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.1
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.305/

Host:
  Version:      7.0.8
  Architecture: arm64
  Commit:       4b0550942d

.NET SDKs installed:
  6.0.411 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]
  7.0.305 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

echo $PATH | grep dotnet
```
/usr/local/share/dotnet/sdk/7.0.305
/usr/local/share/dotnet/dotnet
/usr/local/share/dotnet/dotnet
/usr/local/share/dotnet
~/.dotnet/tools
/Users/alex/.dotnet/tools
/Users/alex/.dotnet/tools
```

**Comment by Akronae** [comment]
I've been able to resolve this issue with this settings
```js
```

**Comment by goenning** [comment]
Same issue here, nothing `omnisharp` in my settings.json.

`dotnet --info` works fine

**Comment by Akronae** [comment]
> @Akronae Do you have any other settings set for `omnisharp` in your `settings.json`?

These are all of my c# related settings
```
  "omnisharp.enableRoslynAnalyzers": true,
  "omnisharp.organizeImportsOnFormat": true,
  "omnisharp.dotnetPath": "/usr/local/share/dotnet/dotnet",
  "omnisharp.sdkPath": "/usr/local/share/dotnet/sdk/7.0.306",
  "csharp.referencesCodeLens.enabled": false,
```

**Comment by jasonmalinowski** [comment]
@Akronae 2.1.2 is uploading right now which should carry some of the fixes we had for macOS. If you delete these lines:

  "omnisharp.dotnetPath": "/usr/local/share/dotnet/dotnet",
  "omnisharp.sdkPath": "/usr/local/share/dotnet/sdk/7.0.306",

Hopefully it should work now.

**Comment by johnborges** [comment]
Update worked for me. Thanks!

**Comment by Akronae** [comment]
@jasonmalinowski I can confirm it seems to be working for me as well 🎉 Good job
