### ISSUE TITLE
DevKit Unreproducible bug:  `Quick Fix...` actions appear, but don't complete

### ISSUE THREAD

**Issue by josh-hemphill** [dotnet/vscode-csharp#6106]
## Environment data
`dotnet --info` output:
VS Code version: 1.81.1
C# Extension version: v2.9.346

## OmniSharp log
none

## Steps to reproduce
unknown

## Expected  behavior
For the listed quick fixes to apply

## Actual behavior
The quick fixes list just fine, and I can even load them in the refactoring preview, but actually applying it just fails silently.

I've searched as best as I can similar issues, to no avail, so any help or direction would be welcome.

**Comment by Mrcubix** [comment]
can reproduce, vscode's Windows produce the following stacktrace:

```log
2023-08-11 01:24:51.469 [error] Unable to resolve resource c:%5CUsers%5Ctinta%5CDocuments%5CRepo%5CC#%5CBannerlord%5CFarmerlord%5CEntities%5CCrops%5CScripts%/StandingPointForMainAgent.cs: Error: Unable to resolve resource [...]/StandingPointForMainAgent.cs
    at r.m (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2308:37515)
    at r.m (vscode-file://vscode-app/[...]/workbench.desktop.main.js:2308:37501)
    at async d.acquire (vscode-file://vscode-app/[...]/workbench.desktop.main.js:19:30395)
    at async c.createModelReference (vscode-file://vscode-app/[...]/workbench.desktop.main.js:2308:38836)
    at async Promise.all (index 0)
    at async r.p (vscode-file://vscode-app/[...]/workbench.desktop.main.js:770:10800)
    at async r.apply (vscode-file://vscode-app/[...]/workbench.desktop.main.js:770:10942)
    at async m.o (vscode-file://vscode-app/[...]/workbench.desktop.main.js:2319:22800)
    at async m.perform (vscode-file://vscode-app/[...]/workbench.desktop.main.js:2319:22377)
    at async h.apply (vscode-file://vscode-app/[...]/workbench.desktop.main.js:2319:24090)
    at async h (vscode-file://vscode-app/[...]/workbench.desktop.main.js:663:61045)
    at async _a.p (vscode-file://vscode-app/[...]/workbench.desktop.main.js:698:47907)
```
no sensitive information is shared in the previous stacktrace

**Comment by dibarbet** [comment]
Thanks - there's an issue with URIs in the prerelease version.  It's been fixed in https://github.com/dotnet/vscode-csharp/pull/6091 and we're planning another release this week.
