### ISSUE TITLE
Projects won't load if you have net8.0 sdk installed

### ISSUE THREAD

**Issue by hez2010** [dotnet/vscode-csharp#6126]
Projects won't load if you have net8.0 sdk installed. Even if you are working with net7.0 projects, they still won't load due to the existence of net8.0 sdk. 

## Environment data
C# Extension version: 2.0.357

**Comment by hez2010** [comment]
> installing C# Dev Kit I believe is a workaround

Installing C# Dev Kit doesn't help.

**Comment by jasonmalinowski** [comment]
Oh strange. @hez2010 are there any errors in the C# output window that you can share that are giving errors?

**Comment by jasonmalinowski** [comment]
Also what is your output of `dotnet --list-sdks`?

**Comment by hez2010** [comment]
Output from "C#":

```
Dotnet path: /Users/***/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
[Info  - 4:03:23] [Program]Language server initialized
[Error - 4:03:23] [LanguageServerHost]System.InvalidOperationException: Was not able to get hello world response from remote - line 39
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.HelloWorld.RemoteHelloWorldProvider.SayHelloToRemoteServerAsync(CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/RemoteHelloWorldProvider.cs:line 39
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.ServiceBrokerFactory.CreateAndConnectAsync(String brokeredServicePipeName) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/ServiceBrokerFactory.cs:line 82
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
```

From "C# Dev Kit":
```
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Starting Spawn .NET server...
.NET server started and IPC established in 1536ms
Completed Spawn .NET server (1546ms)
Completed Clear environment (1711ms)
Completed Open a solution with environment service (1863ms)
Starting Restore solution...
Completed Open a solution (1873ms)
Completed Restore solution (1054ms)
```

From "Projects":
```
[info] Project system initialization finished. 0 project(s) are loaded, and 1 failed to load.
```

And `dotnet --list-sdks`:

```
7.0.400 [/usr/local/share/dotnet/sdk]
8.0.100-preview.7.23376.3 [/usr/local/share/dotnet/sdk]
```

BTW I'm on macOS.

**Comment by vchirikov** [comment]
I saw the same, for some reason vscode-csharp trying to use net7, I deleted net7 and vscode-csharp can't load a csproj with net8-preview:

```
Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# standalone...
[Info  - 12:40:20 PM] [Program]Language server initialized
[Info  - 12:40:20 PM] [LanguageServerProjectSystem]Loaded MSBuild at C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3
[Info  - 12:40:20 PM] [LanguageServerProjectSystem]Loading <Solution>.sln...
[Error - 12:40:21 PM] [LanguageServerProjectSystem]Failure while loading <PATH>src\Shared\Shared.csproj: The "CheckIfPackageReferenceShouldBeFrameworkReference" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\..\tools\net8.0\Microsoft.NET.Build.Tasks.dll. Could not load type 'System.Runtime.CompilerServices.NullableContextAttribute' from assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

dotnet info:
```
Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: x64
  Commit:       65b696cf5e
  RID:          win-x64

.NET SDKs installed:
  6.0.408 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]
```

**Comment by hez2010** [comment]
The only workaround is to uninstall C# Dev Kit and check the `Use OmniSharp` in C# extension settings.

**Comment by vchirikov** [comment]
@jasonmalinowski it isn't fixed yet, at least without a roslyn update in the repo, isn't it?

**Comment by jasonmalinowski** [comment]
@vchirikov We updated Roslyn in this repo with https://github.com/dotnet/vscode-csharp/pull/6285; we're currently working on getting a prerelease build posted with it.

**Comment by jasonmalinowski** [comment]
@vchirikov 2.2.10 is now out if you want to give that a shot. It's pre-release only at the moment, but you can easily switch back and forth. [Instructions are here.](https://github.com/dotnet/vscode-csharp/discussions/6320)

**Comment by RuiAlias** [comment]
I'm still affected by this problem. On Windows 10, with VSCode Insiders, C# extension v2.2.10: with .NET 8 SDK (8.0.100-rc.1.23463.5) all projects fail loading. Uninstalling .NET 8 SDK fixes the issue.

Output of "C#":
```
Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
[Info  - 4:39:29 PM] [Program] Language server initialized
```

Output of "C# Dev Kit"
```
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
.NET server started and IPC established in 1017ms
Completed Spawn .NET server (1160ms)
Completed Clear environment (1609ms)
Completed Open a solution with environment service (1653ms)
Starting Restore solution...
Completed Open a solution (1669ms)
Completed Restore solution (8550ms)
```

Output of "Projects"
```
2023-09-19 16:39:37.137 [info] Project system initialization finished. 0 project(s) are loaded, and 86 failed to load.
```

Output of "dotnet --list-sdks"
```
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.404 [C:\Program Files\dotnet\sdk]
5.0.416 [C:\Program Files\dotnet\sdk]
6.0.101 [C:\Program Files\dotnet\sdk]
6.0.200 [C:\Program Files\dotnet\sdk]
7.0.304 [C:\Program Files\dotnet\sdk]
7.0.306 [C:\Program Files\dotnet\sdk]
7.0.401 [C:\Program Files\dotnet\sdk]
8.0.100-rc.1.23463.5 [C:\Program Files\dotnet\sdk]
```

**Comment by lifengl** [comment]
can you tell us the version of C# Dev Kit you are using, and whether you have setting dotnet.preferRuntimeFromSDK enabled or not (we are phasing out this setting, but the earlier version CDK still uses it).

It was a problem that older version CDK is incompatible with new builds of NET 8 SDKs. You are more likely to have this problem by using the extension from its 'release' channel (as it was up to a month older than 'pre-release' one).

C# Dev Kit adds a "projects" output panel, which may provide some information on what might go wrong (and if it doesn't contain helpful information, it would be helpful to open the extension log folder, and find ServiceHub folder inside CDK logging data. There are at least two *Composition*.log files in the folder, which may give us some clue here.

**Comment by lifengl** [comment]
BTW, if you expand projects failed to load, what is the error message string?

**Comment by RuiAlias** [comment]
Nevermind, I was not running the latest version of CDK and neither of VSCode Insiders. Upgrading both fixed my issue. Thanks.
