### ISSUE TITLE
Rosyln failing to start on Mac x64 with 'image not found' error for hostfxr.dylib

### ISSUE THREAD

**Issue by v-Judy** [dotnet/vscode-csharp#6198]
## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
Version: 6.0.317
Commit:    98282dc4ea
Runtime Environment:
OS Name:     Mac OS X
OS Version:  11.6
OS Platform: Darwin
RID:         osx.11.0-x64
Base Path:   /usr/local/share/dotnet/sdk/6.0.317/
global.json file:
  Not found
Host:
  Version:      6.0.22
  Architecture: x64
  Commit:       ad40cc35b5
.NET SDKs installed:
  6.0.317 [/usr/local/share/dotnet/sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
**VS Code version:**  1.81.1
**C# Extension version:** v2.0.376

## Omnisharp log
<details> <summary>C# log</summary>Version:1.0
StartHTML:000000096
EndHTML:000005287
StartFragment:000000186
EndFragment:000005273

Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime

Found dotnet version 6.0.22. Minimum required version is 7.0.100.

Dotnet path: /Users/vs/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/dotnet

Activating C# standalone...

[Info  - 4:26:50 PM] [Program]Language server initialized

[Error - 4:26:51 PM] [LanguageServerHost]System.DllNotFoundException: Unable to load shared library 'hostfxr' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:

dlopen(/Users/vs/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/shared/Microsoft.NETCore.App/7.0.10/hostfxr.dylib, 1): image not found

dlopen(/Users/vs/.vscode/extensions/ms-dotnettools.csharp-2.0.376-darwin-x64/.roslyn/hostfxr.dylib, 1): image not found

dlopen(hostfxr.dylib, 1): image not found

dlopen(/Users/vs/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/shared/Microsoft.NETCore.App/7.0.10/libhostfxr.dylib, 1): image not found

dlopen(/Users/vs/.vscode/extensions/ms-dotnettools.csharp-2.0.376-darwin-x64/.roslyn/libhostfxr.dylib, 1): image not found

dlopen(libhostfxr.dylib, 1): image not found

dlopen(/Users/vs/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/shared/Microsoft.NETCore.App/7.0.10/hostfxr, 1): image not found

dlopen(/Users/vs/.vscode/extensions/ms-dotnettools.csharp-2.0.376-darwin-x64/.roslyn/hostfxr, 1): image not found

dlopen(hostfxr, 1): image not found

dlopen(/Users/vs/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/shared/Microsoft.NETCore.App/7.0.10/libhostfxr, 1): image not found

dlopen(/Users/vs/.vscode/extensions/ms-dotnettools.csharp-2.0.376-darwin-x64/.roslyn/libhostfxr, 1): image not found

dlopen(libhostfxr, 1): image not found

 

   at Microsoft.Build.Locator.NativeMethods.hostfxr_resolve_sdk2(String exe_dir, String working_dir, hostfxr_resolve_sdk2_flags_t flags, hostfxr_resolve_sdk2_result_fn result)

   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()

   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()

   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()

   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()

   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)

   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)

   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.TryEnsureMSBuildLoadedAsync(String workingDirectory) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 140

   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenProjectsAsync(ImmutableArray`1 projectFilePaths) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 112

   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136</details>

## Steps to reproduce
1. Create a folder and create a angular project in it:
```
mkdir Angular
cd Angular
dotnet new angular
```
2. Navigate to the folder you created Angular and open VS Code using Terminal Emulator.
```
code .
```
3. F5 to run the project.

## Note
1. This issue only repro on Mac BigSur OS
2. This issue does not repro on **C# v1.26.0**

## Actual behavior
An error pop up after F5 to run the project:
![MicrosoftTeams-image](https://github.com/dotnet/vscode-csharp/assets/108645282/94fe8a46-7cfb-446a-bf08-046eab823cdb)
![image](https://github.com/dotnet/vscode-csharp/assets/108645282/2ad8cb31-4350-4968-9ede-437484f3156a)

**Comment by dibarbet** [comment]
@jasonmalinowski since you have an x64 mac, mind taking the first look?  The extension platform and os platform and dotnet platform seem to match.

**Comment by JoeRobich** [comment]
Seems related to https://github.com/microsoft/MSBuildLocator/pull/230

**Comment by dibarbet** [comment]
That does indeed look incredibly related.  Thanks for the link!
