### ISSUE TITLE
Exception After Creating New File

### ISSUE THREAD

**Issue by jtsom** [dotnet/vscode-csharp#6241]
Type: <b>Bug</b>

## Issue Description ##
Using C# Dev Kit, after creating a new class file, an error notification was generated as soon as first character is typed in the new class:

![image](https://github.com/dotnet/vscode-csharp/assets/13488/60970fd4-1dbd-4690-bad0-fda7917ae877)

## Steps to Reproduce ##
Right click on folder, Choose New Item. Select Class, enter name.

## Expected Behavior ##
No error.
## Actual Behavior ##
Error shown.

### C# log ###
<details>
[Error - 12:08:35 PM] [LanguageServerHost]System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.TryGetUpdatedDocumentDiagnostics(DocumentAnalysisData existingData, ImmutableArray`1 oldMemberSpans, ImmutableArray`1 memberDiagnostics, SyntaxTree tree, SourceText text, SyntaxNode member, Int32 memberId, ImmutableArray`1& updatedDiagnostics) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs:line 297
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.GetUpdatedDiagnosticsForMemberEditAsync(ImmutableArray`1 diagnostics, DocumentAnalysisData existingData, DiagnosticAnalyzer analyzer, DocumentAnalysisExecutor executor, SyntaxNode changedMember, Int32 changedMemberId, ImmutableArray`1 oldMemberSpans, Func`4 computeAnalyzerDiagnosticsAsync, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs:line 261
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.<>c__DisplayClass2_0.<<ComputeDiagnosticsAsync>g__ExecuteAnalyzersAsync|3>d.MoveNext() in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs:line 190
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.<>c__DisplayClass2_0.<<ComputeDiagnosticsAsync>g__ExecuteCompilerAnalyzerAsync|0>d.MoveNext() in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs:line 141
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.ComputeDiagnosticsAsync(DocumentAnalysisExecutor executor, ImmutableArray`1 analyzersWithState, VersionStamp version, Func`4 computeAnalyzerDiagnosticsAsync, Func`3 computeDiagnosticsNonIncrementallyAsync, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs:line 117
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.ComputeDocumentDiagnosticsAsync(ImmutableArray`1 analyzersWithState, AnalysisKind kind, Nullable`1 span, ArrayBuilder`1 builder, Boolean incrementalAnalysis, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 559
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetAsync(ArrayBuilder`1 list, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 367
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.TryAppendDiagnosticsForSpanAsync(TextDocument document, Nullable`1 range, ArrayBuilder`1 result, Func`2 shouldIncludeDiagnostic, Boolean includeSuppressedDiagnostics, Boolean includeCompilerDiagnostics, ICodeActionRequestPriorityProvider priorityProvider, Boolean blockForData, Func`2 addOperationScope, DiagnosticKind diagnosticKinds, Boolean isExplicit, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 35
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.GetDiagnosticsForSpanAsync(TextDocument document, Nullable`1 range, Func`2 shouldIncludeDiagnostic, Boolean includeSuppressedDiagnostics, Boolean includeCompilerDiagnostics, ICodeActionRequestPriorityProvider priorityProvider, Boolean blockForData, Func`2 addOperationScope, DiagnosticKind diagnosticKinds, Boolean isExplicit, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 56
   at Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.DocumentDiagnosticSource.GetDiagnosticsAsync(IDiagnosticAnalyzerService diagnosticAnalyzerService, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/DocumentDiagnosticSource.cs:line 30
   at Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.AbstractPullDiagnosticHandler`3.ComputeAndReportCurrentDiagnosticsAsync(RequestContext context, IDiagnosticSource diagnosticSource, BufferedProgress`1 progress, String resultId, ClientCapabilities clientCapabilities, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs:line 283
   at Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.AbstractPullDiagnosticHandler`3.HandleRequestAsync(TDiagnosticsParams diagnosticsParams, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs:line 179
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
[Error - 12:08:35 PM] [LanguageServerHost]System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.TryGetUpdatedDocumentDiagnostics(DocumentAnalysisData existingData, ImmutableArray`1 oldMemberSpans, ImmutableArray`1 memberDiagnostics, SyntaxTree tree, SourceText text, SyntaxNode member, Int32 memberId, ImmutableArray`1& updatedDiagnostics) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs:line 297
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.GetUpdatedDiagnosticsForMemberEditAsync(ImmutableArray`1 diagnostics, DocumentAnalysisData existingData, DiagnosticAnalyzer analyzer, DocumentAnalysisExecutor executor, SyntaxNode changedMember, Int32 changedMemberId, ImmutableArray`1 oldMemberSpans, Func`4 computeAnalyzerDiagnosticsAsync, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs:line 261
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.<>c__DisplayClass2_0.<<ComputeDiagnosticsAsync>g__ExecuteAnalyzersAsync|3>d.MoveNext() in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs:line 190
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.<>c__DisplayClass2_0.<<ComputeDiagnosticsAsync>g__ExecuteCompilerAnalyzerAsync|0>d.MoveNext() in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs:line 141
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.ComputeDiagnosticsAsync(DocumentAnalysisExecutor executor, ImmutableArray`1 analyzersWithState, VersionStamp version, Func`4 computeAnalyzerDiagnosticsAsync, Func`3 computeDiagnosticsNonIncrementallyAsync, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.IncrementalMemberEditAnalyzer.cs:line 117
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.ComputeDocumentDiagnosticsAsync(ImmutableArray`1 analyzersWithState, AnalysisKind kind, Nullable`1 span, ArrayBuilder`1 builder, Boolean incrementalAnalysis, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 559
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetAsync(ArrayBuilder`1 list, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 367
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.TryAppendDiagnosticsForSpanAsync(TextDocument document, Nullable`1 range, ArrayBuilder`1 result, Func`2 shouldIncludeDiagnostic, Boolean includeSuppressedDiagnostics, Boolean includeCompilerDiagnostics, ICodeActionRequestPriorityProvider priorityProvider, Boolean blockForData, Func`2 addOperationScope, DiagnosticKind diagnosticKinds, Boolean isExplicit, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 35
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.GetDiagnosticsForSpanAsync(TextDocument document, Nullable`1 range, Func`2 shouldIncludeDiagnostic, Boolean includeSuppressedDiagnostics, Boolean includeCompilerDiagnostics, ICodeActionRequestPriorityProvider priorityProvider, Boolean blockForData, Func`2 addOperationScope, DiagnosticKind diagnosticKinds, Boolean isExplicit, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs:line 56
   at Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.DocumentDiagnosticSource.GetDiagnosticsAsync(IDiagnosticAnalyzerService diagnosticAnalyzerService, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Diagnostics/DiagnosticSources/DocumentDiagnosticSource.cs:line 30
   at Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.AbstractPullDiagnosticHandler`3.ComputeAndReportCurrentDiagnosticsAsync(RequestContext context, IDiagnosticSource diagnosticSource, BufferedProgress`1 progress, String resultId, ClientCapabilities clientCapabilities, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs:line 283
   at Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.AbstractPullDiagnosticHandler`3.HandleRequestAsync(TDiagnosticsParams diagnosticsParams, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Diagnostics/AbstractPullDiagnosticHandler.cs:line 179
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
[Error - 12:08:35 PM] Request textDocument/diagnostic failed.
  Message: Index was outside the bounds of the array.
  Code: -32000 
[object Object]
[Error - 12:08:35 PM] Document pull failed for text document file:///d%3A/source/EF-API/EF-API/Extensions/ServiceExtensions.cs
  Message: Index was outside the bounds of the array.
  Code: -32000 
[object Object]

</details>

### C# LSP Trace Logs ###
<details>Extension vscode.bat does not contribute csharpExtensionLoadPaths
Extension vscode.clojure does not contribute csharpExtensionLoadPaths
Extension vscode.coffeescript does not contribute csharpExtensionLoadPaths
Extension vscode.configuration-editing does not contribute csharpExtensionLoadPaths
Extension vscode.cpp does not contribute csharpExtensionLoadPaths
Extension vscode.csharp does not contribute csharpExtensionLoadPaths
Extension vscode.css does not contribute csharpExtensionLoadPaths
Extension vscode.css-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.dart does not contribute csharpExtensionLoadPaths
Extension vscode.debug-auto-launch does not contribute csharpExtensionLoadPaths
Extension vscode.debug-server-ready does not contribute csharpExtensionLoadPaths
Extension vscode.diff does not contribute csharpExtensionLoadPaths
Extension vscode.docker does not contribute csharpExtensionLoadPaths
Extension vscode.emmet does not contribute csharpExtensionLoadPaths
Extension vscode.extension-editing does not contribute csharpExtensionLoadPaths
Extension vscode.fsharp does not contribute csharpExtensionLoadPaths
Extension vscode.git does not contribute csharpExtensionLoadPaths
Extension vscode.git-base does not contribute csharpExtensionLoadPaths
Extension vscode.github does not contribute csharpExtensionLoadPaths
Extension vscode.github-authentication does not contribute csharpExtensionLoadPaths
Extension vscode.go does not contribute csharpExtensionLoadPaths
Extension vscode.groovy does not contribute csharpExtensionLoadPaths
Extension vscode.grunt does not contribute csharpExtensionLoadPaths
Extension vscode.gulp does not contribute csharpExtensionLoadPaths
Extension vscode.handlebars does not contribute csharpExtensionLoadPaths
Extension vscode.hlsl does not contribute csharpExtensionLoadPaths
Extension vscode.html does not contribute csharpExtensionLoadPaths
Extension vscode.html-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.ini does not contribute csharpExtensionLoadPaths
Extension vscode.ipynb does not contribute csharpExtensionLoadPaths
Extension vscode.jake does not contribute csharpExtensionLoadPaths
Extension vscode.java does not contribute csharpExtensionLoadPaths
Extension vscode.javascript does not contribute csharpExtensionLoadPaths
Extension vscode.json does not contribute csharpExtensionLoadPaths
Extension vscode.json-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.julia does not contribute csharpExtensionLoadPaths
Extension vscode.latex does not contribute csharpExtensionLoadPaths
Extension vscode.less does not contribute csharpExtensionLoadPaths
Extension vscode.log does not contribute csharpExtensionLoadPaths
Extension vscode.lua does not contribute csharpExtensionLoadPaths
Extension vscode.make does not contribute csharpExtensionLoadPaths
Extension vscode.markdown does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-math does not contribute csharpExtensionLoadPaths
Extension vscode.media-preview does not contribute csharpExtensionLoadPaths
Extension vscode.merge-conflict does not contribute csharpExtensionLoadPaths
Extension vscode.microsoft-authentication does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-wsl-recommender does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug-companion does not contribute csharpExtensionLoadPaths
Extension ms-vscode.vscode-js-profile-table does not contribute csharpExtensionLoadPaths
Extension vscode.builtin-notebook-renderers does not contribute csharpExtensionLoadPaths
Extension vscode.npm does not contribute csharpExtensionLoadPaths
Extension vscode.objective-c does not contribute csharpExtensionLoadPaths
Extension vscode.perl does not contribute csharpExtensionLoadPaths
Extension vscode.php does not contribute csharpExtensionLoadPaths
Extension vscode.php-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.powershell does not contribute csharpExtensionLoadPaths
Extension vscode.pug does not contribute csharpExtensionLoadPaths
Extension vscode.python does not contribute csharpExtensionLoadPaths
Extension vscode.r does not contribute csharpExtensionLoadPaths
Extension vscode.razor does not contribute csharpExtensionLoadPaths
Extension vscode.references-view does not contribute csharpExtensionLoadPaths
Extension vscode.restructuredtext does not contribute csharpExtensionLoadPaths
Extension vscode.ruby does not contribute csharpExtensionLoadPaths
Extension vscode.rust does not contribute csharpExtensionLoadPaths
Extension vscode.scss does not contribute csharpExtensionLoadPaths
Extension vscode.search-result does not contribute csharpExtensionLoadPaths
Extension vscode.shaderlab does not contribute csharpExtensionLoadPaths
Extension vscode.shellscript does not contribute csharpExtensionLoadPaths
Extension vscode.simple-browser does not contribute csharpExtensionLoadPaths
Extension vscode.sql does not contribute csharpExtensionLoadPaths
Extension vscode.swift does not contribute csharpExtensionLoadPaths
Extension vscode.theme-abyss does not contribute csharpExtensionLoadPaths
Extension vscode.theme-defaults does not contribute csharpExtensionLoadPaths
Extension vscode.theme-kimbie-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai-dimmed does not contribute csharpExtensionLoadPaths
Extension vscode.theme-quietlight does not contribute csharpExtensionLoadPaths
Extension vscode.theme-red does not contribute csharpExtensionLoadPaths
Extension vscode.vscode-theme-seti does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-light does not contribute csharpExtensionLoadPaths
Extension vscode.theme-tomorrow-night-blue does not contribute csharpExtensionLoadPaths
Extension vscode.tunnel-forwarding does not contribute csharpExtensionLoadPaths
Extension vscode.typescript does not contribute csharpExtensionLoadPaths
Extension vscode.typescript-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.vb does not contribute csharpExtensionLoadPaths
Extension vscode.xml does not contribute csharpExtensionLoadPaths
Extension vscode.yaml does not contribute csharpExtensionLoadPaths
Extension adamhartford.vscode-base64 does not contribute csharpExtensionLoadPaths
Extension albert.TabOut does not contribute csharpExtensionLoadPaths
Extension dqisme.sync-scroll does not contribute csharpExtensionLoadPaths
Extension fabianlauer.vs-code-xml-format does not contribute csharpExtensionLoadPaths
Extension kreativ-software.csharpextensions does not contribute csharpExtensionLoadPaths
Extension mechatroner.rainbow-csv does not contribute csharpExtensionLoadPaths
Extension mhutchie.git-graph does not contribute csharpExtensionLoadPaths
Extension mitchdenny.ecdc does not contribute csharpExtensionLoadPaths
Extension ms-azuretools.vscode-azureappservice does not contribute csharpExtensionLoadPaths
Extension ms-azuretools.vscode-azurefunctions does not contribute csharpExtensionLoadPaths
Extension ms-azuretools.vscode-azureresourcegroups does not contribute csharpExtensionLoadPaths
Extension ms-azuretools.vscode-azurestorage does not contribute csharpExtensionLoadPaths
Extension ms-azuretools.vscode-cosmosdb does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csdevkit does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csharp does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.vscode-dotnet-runtime does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.vscodeintellicode-csharp does not contribute csharpExtensionLoadPaths
Extension ms-vscode.azure-account does not contribute csharpExtensionLoadPaths
Extension ms-vscode.hexeditor does not contribute csharpExtensionLoadPaths
Extension ms-vscode.live-server does not contribute csharpExtensionLoadPaths
Extension oderwat.indent-rainbow does not contribute csharpExtensionLoadPaths
Extension PKief.material-icon-theme does not contribute csharpExtensionLoadPaths
Extension qufiwefefwoyn.kanagawa does not contribute csharpExtensionLoadPaths
Extension quicktype.quicktype does not contribute csharpExtensionLoadPaths
Extension rangav.vscode-thunder-client does not contribute csharpExtensionLoadPaths
Extension RobHolme.hl7tools does not contribute csharpExtensionLoadPaths
Extension sdras.night-owl does not contribute csharpExtensionLoadPaths
Extension tintoy.msbuild-project-tools does not contribute csharpExtensionLoadPaths
Extension VisualStudioExptTeam.vscodeintellicode does not contribute csharpExtensionLoadPaths
Extension yokawasa.jwt-debugger does not contribute csharpExtensionLoadPaths
</details>

## Environment information ##

**VSCode version**: 1.82.0-insider
**C# Extension**: 2.0.413
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
Error running dotnet --info: Error: Command failed: C:\Program Files\dotnet\dotnet.exe --info
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.5|ms-vscode.azure-account-0.11.5|
|csdevkit|ms-dotnettools|0.4.6|ms-dotnettools.csdevkit-0.4.6-win32-x64|
|csharp|ms-dotnettools|2.0.413|ms-dotnettools.csharp-2.0.413-win32-x64|
|csharpextensions|kreativ-software|1.7.3|kreativ-software.csharpextensions-1.7.3|
|ecdc|mitchdenny|1.8.0|mitchdenny.ecdc-1.8.0|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|hl7tools|RobHolme|2.0.4|robholme.hl7tools-2.0.4|
|indent-rainbow|oderwat|8.3.1|oderwat.indent-rainbow-8.3.1|
|jwt-debugger|yokawasa|0.4.2|yokawasa.jwt-debugger-0.4.2|
|kanagawa|qufiwefefwoyn|1.5.1|qufiwefefwoyn.kanagawa-1.5.1|
|live-server|ms-vscode|0.4.9|ms-vscode.live-server-0.4.9|
|material-icon-theme|PKief|4.30.0|pkief.material-icon-theme-4.30.0|
|msbuild-project-tools|tintoy|0.4.9|tintoy.msbuild-project-tools-0.4.9|
|night-owl|sdras|2.0.1|sdras.night-owl-2.0.1|
|quicktype|quicktype|12.0.46|quicktype.quicktype-12.0.46|
|rainbow-csv|mechatroner|3.7.0|mechatroner.rainbow-csv-3.7.0|
|sync-scroll|dqisme|1.3.1|dqisme.sync-scroll-1.3.1|
|TabOut|albert|0.2.2|albert.tabout-0.2.2|
|vs-code-xml-format|fabianlauer|0.1.5|fabianlauer.vs-code-xml-format-0.1.5|
|vscode-azureappservice|ms-azuretools|0.25.0|ms-azuretools.vscode-azureappservice-0.25.0|
|vscode-azurefunctions|ms-azuretools|1.12.4|ms-azuretools.vscode-azurefunctions-1.12.4|
|vscode-azureresourcegroups|ms-azuretools|0.7.5|ms-azuretools.vscode-azureresourcegroups-0.7.5|
|vscode-azurestorage|ms-azuretools|0.15.3|ms-azuretools.vscode-azurestorage-0.15.3|
|vscode-base64|adamhartford|0.1.0|adamhartford.vscode-base64-0.1.0|
|vscode-cosmosdb|ms-azuretools|0.19.4|ms-azuretools.vscode-cosmosdb-0.19.4|
|vscode-dotnet-runtime|ms-dotnettools|1.7.1|ms-dotnettools.vscode-dotnet-runtime-1.7.1|
|vscode-thunder-client|rangav|2.10.5|rangav.vscode-thunder-client-2.10.5|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>

Extension version: 2.0.413
VS Code version: Code - Insiders 1.82.0-insider (f7973f357e7c316a88e8817886f41a843021fe74, 2023-08-28T05:35:52.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (11.26GB free)|
|Process Argv|--crash-reporter-id 362817d9-b661-4b35-92b7-fe18e5872851|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
vscrp:30624060
a9j8j154:30646983
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmpsinfo:30815194
dsvsc015:30821418

```

</details>

**Comment by arkalyanms** [comment]
@jtsom Thanks for filing! Would you please share your C# log and if possible a project where you hit the repro?

**Comment by jtsom** [comment]
This was in a simple C# web api project. The C# log is listed in the report, under the section labeled "C# Logs".

**Comment by beccamc** [comment]
@jtsom This looks to be fixed. Can you check?

**Comment by jtsom** [comment]
Yes I have not run into this issue, so it does look fixed.

Thanks!
