### ISSUE TITLE
Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.

### ISSUE THREAD

**Issue by 4ColorDesign** [dotnet/vscode-csharp#6242]
# Describe the bug
  Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
No compatible .NET runtime found. Minimum required version is 7.0.
[Error - 4:13:01 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Could not resolve the dotnet path!
    at t.DotnetRuntimeExtensionResolver.<anonymous> (c:\Users\atulm\.vscode\extensions\ms-dotnettools.csharp-2.0.413-win32-x64\dist\extension.js:2:1382303)
    at Generator.next (<anonymous>)
    at s (c:\Users\atulm\.vscode\extensions\ms-dotnettools.csharp-2.0.413-win32-x64\dist\extension.js:2:1380683)

  
  
  ## **Please attach log file(s) here if you have any:**
  >❗ Privacy Alert! The contents in our log files may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement
  
  
  
  If you came here from VS Code, the log file location should be copied to the clipboard.
  
  ## Other Info:
  Errors the extension may have encountered have likely been added to your terminal or VS Code windows. Please paste it/them here and describe what happened and the problem you are facing.
  
  **Reproduction Steps**
  
  
  **Expected behavior**
  
  
  **Exceptions & Errors (if any)**
  
  
  **Further technical details**
  - Your VSCode Version
  
  - The version of the extension that's on your machine
  
  - Your operating system details

**Comment by Hongmo97** [comment]
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (x64) does not match the architecture of the extension (x86).
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit...
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:15:33] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:15:33] Connection to server got closed. Server will restart.
true
[Error - 10:15:33] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (x64) does not match the architecture of the extension (x86).
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit...
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:15:33] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:15:33] Connection to server got closed. Server will restart.
true
[Error - 10:15:33] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (x64) does not match the architecture of the extension (x86).
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit...
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:15:34] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:15:34] Connection to server got closed. Server will restart.
true
[Error - 10:15:34] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:15:34] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (x64) does not match the architecture of the extension (x86).
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit...
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:15:34] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:15:34] Connection to server got closed. Server will restart.
true
[Error - 10:15:34] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:15:34] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (x64) does not match the architecture of the extension (x86).
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit...
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:15:34] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:15:34] The Microsoft.CodeAnalysis.LanguageServer server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:15:34] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:15:34] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097

**Comment by dibarbet** [comment]
@Hongmo97 I filed a separate issue for your report here since its a different problem - https://github.com/dotnet/vscode-csharp/issues/6258

**Comment by dibarbet** [comment]
@4ColorDesign mind posting the output of running `dotnet --info` here?

@nagilson I believe this issue is still on the runtime extension side.  Essentially what is happening here is we fail to find a .net7 runtime on the path, so we fallback to the runtime extension.  And the call to the runtime extension is returning nothing here - https://github.com/dotnet/vscode-csharp/blob/main/src/lsptoolshost/dotnetRuntimeExtensionResolver.ts#L98

**Comment by nagilson** [comment]
Sorry, I will investigate that further. That shouldn't happen. @4ColorDesign May you please send the log as the attached issue template had suggested so we can investigate? Thanks.
