### ISSUE TITLE
[BUG] Request textDocument/completion failed.

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/vscode-csharp#6308]
From vscode-dotnettools created by [mystiquewolf](https://github.com/mystiquewolf): microsoft/vscode-dotnettools#450  

### Describe the Issue

Typing into c# file gives
```
Using dotnet configured on PATH
Dotnet path: /usr/share/dotnet/dotnet
Activating C# + C# Dev Kit...
[Info  - 12:37:30] [Program]Language server initialized
[Error - 12:38:24] [LanguageServerHost]System.InvalidOperationException: Unexpected null - line 114
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractOverrideCompletionProvider.ItemGetter.TryDetermineOverridableMembers(SemanticModel semanticModel, SyntaxToken startToken, Accessibility seenAccessibility, ImmutableArray`1& overridableMembers) in /_/src/Features/Core/Portable/Completion/Providers/AbstractOverrideCompletionProvider.ItemGetter.cs:line 113
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractOverrideCompletionProvider.ItemGetter.GetItemsAsync() in /_/src/Features/Core/Portable/Completion/Providers/AbstractOverrideCompletionProvider.ItemGetter.cs:line 77
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractOverrideCompletionProvider.ProvideCompletionsAsync(CompletionContext context) in /_/src/Features/Core/Portable/Completion/Providers/AbstractOverrideCompletionProvider.cs:line 31
   at Microsoft.CodeAnalysis.Completion.CompletionService.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, CompletionOptions options, TextSpan defaultSpan, SharedSyntaxContextsWithSpeculativeModel sharedContext, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs:line 322
   at Microsoft.CodeAnalysis.Completion.CompletionService.ComputeNonEmptyCompletionContextsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, CompletionOptions options, TextSpan completionListSpan, ImmutableArray`1 providers, SharedSyntaxContextsWithSpeculativeModel sharedContext, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs:line 240
   at Microsoft.CodeAnalysis.Completion.CompletionService.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionOptions options, OptionSet passThroughOptions, CompletionTrigger trigger, ImmutableHashSet`1 roles, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs:line 93
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CompletionHandler.CalculateListAsync(CompletionParams request, Document document, Int32 position, CompletionTrigger completionTrigger, CompletionOptions completionOptions, CompletionService completionService, CompletionListCache completionListCache, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs:line 129
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CompletionHandler.GetFilteredCompletionListAsync(CompletionParams request, RequestContext context, SourceText sourceText, Document document, CompletionOptions completionOptions, CompletionService completionService, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs:line 103
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CompletionHandler.HandleRequestAsync(CompletionParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs:line 67
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 176
[Error - 12:38:24] Request textDocument/completion failed.
  Message: Unexpected null - line 114
  Code: -32000 
[object Object]

```

### Environment Information

openSUSE Tumbleweed
VS Code 1.81.1
C# Dev Kit 0.3.21

**Comment by arkalyanms** [comment]
@genlu would you confirm if this is made better by https://github.com/dotnet/roslyn/pull/69795?

**Comment by genlu** [comment]
No. This failure happened during item calculation phase, the linked PR only dealt with item resolution. I will see if I could figure out a repro

**Comment by onlydemzy** [comment]
I have this vs code Error: "Request textDocument/semanticTokens/range failed. Message: The requested line number 190 must be less than the number of lines 2. (Parameter 'Line') Code: -32000 [object Object]" Whenever I am working with a .razor file.
framework: .net 9.0.3
Application template: Blazor 9
All my extensions are up to date
