### ISSUE TITLE
Formatting razor file leads "Request textDocument/formatting failed" with different line numbers

### ISSUE THREAD

**Issue by garrettlondon1** [dotnet/vscode-csharp#6488]
## Environment data
`dotnet --info` output: .net 7
VS Code version: 
C# Extension version: 2.4.4

Formatting Razor File errors with "Request textDocument/formatting failed" #5561 
https://github.com/dotnet/vscode-csharp/issues/5561#issuecomment-1747766645

Getting an issue formatting the razor file

<img width="773" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/3959577/8a2fdc6d-04e3-4582-9866-43531faa4b23">

**Comment by garrettlondon1** [comment]
@davidwengier what is a good email to send the file to?

**Comment by davidwengier** [comment]
firstname dot lastname at microsoft dot com :)

**Comment by davidwengier** [comment]
Got it, and amazingly, I can repro it!

```
[Error - 11:04:03 AM] System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Range start line 116 matches or exceeds SourceText boundary 114.')
   at Microsoft.AspNetCore.Razor.LanguageServer.Extensions.RangeExtensions.AsTextSpan(Range range, SourceText sourceText) in D:\Code\alt-razor\src\Razor\src\Microsoft.AspNetCore.Razor.LanguageServer\Extensions\RangeExtensions.cs:line 147
   at Microsoft.AspNetCore.Razor.LanguageServer.Extensions.TextEditExtensions.AsTextChange(TextEdit textEdit, SourceText sourceText) in D:\Code\alt-razor\src\Razor\src\Microsoft.AspNetCore.Razor.LanguageServer\Extensions\TextEditExtensions.cs:line 24
   at Microsoft.AspNetCore.Razor.LanguageServer.Formatting.HtmlFormattingPass.<>c__DisplayClass10_0.<ExecuteAsync>b__1(TextEdit e) in D:\Code\alt-razor\src\Razor\src\Microsoft.AspNetCore.Razor.LanguageServer\Formatting\HtmlFormattingPass.cs:line 80
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.Text.SourceText.WithChanges(IEnumerable`1 changes)
   at Microsoft.AspNetCore.Razor.LanguageServer.Formatting.HtmlFormattingPass.ExecuteAsync(FormattingContext context, FormattingResult result, CancellationToken cancellationToken) in D:\Code\alt-razor\src\Razor\src\Microsoft.AspNetCore.Razor.LanguageServer\Formatting\HtmlFormattingPass.cs:line 81
   at Microsoft.AspNetCore.Razor.LanguageServer.Formatting.RazorFormattingService.FormatAsync(VersionedDocumentContext documentContext, Range range, FormattingOptions options, CancellationToken cancellationToken) in D:\Code\alt-razor\src\Razor\src\Microsoft.AspNetCore.Razor.LanguageServer\Formatting\RazorFormattingService.cs:line 75
   at Microsoft.AspNetCore.Razor.LanguageServer.Formatting.DocumentFormattingEndpoint.HandleRequestAsync(DocumentFormattingParams request, RazorRequestContext requestContext, CancellationToken cancellationToken) in D:\Code\alt-razor\src\Razor\src\Microsoft.AspNetCore.Razor.LanguageServer\Formatting\DocumentFormattingEndpoint.cs:line 60
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
[Error - 11:04:03 AM] Request textDocument/formatting failed.
  Message: Specified argument was out of the range of valid values. (Parameter 'Range start line 116 matches or exceeds SourceText boundary 114.')
  Code: -32000 
```

**Comment by garrettlondon1** [comment]
Amazing! Yes, it's fine in VS for me as well!

**Comment by davidwengier** [comment]
.. and its gone. I wonder if I'm reproing the same issue.

For me, when it repro'd, I could use the "Show Razor Html" command in VS Code, and I saw a document that was duplicated, which is to say it contained two copies, one after the other, of the Html portions of the Razor file. Do you see the same thing when you run it?

What that means is that the Razor server and VS Code extension have different opinions about what the contents of the file should be. Definitely a bug, and definitely something we can fix.  Generally speaking though, when that happens, a close/reopen of the file, and/or typing something in the file, will often fix the issue. I get the impression that doesn't happen for you?

I just want to make sure I'm trying to fix the right bug :)

**Comment by garrettlondon1** [comment]
A close and reopen of the file results in the formatting not showing the error toast notification but also failing to format the file

**Comment by davidwengier** [comment]
I've opened a PR that should remove the error hopefully.

Formatting not actually doing anything is normally because we detected that the formatting operation would introduce invalid code (ie, the resulting code has more errors than the before code) or the formatting operation would change some non-whitespace characters. In this case it appears to be because of the rather long C# strings you have in the .razor file. VS Code's html formatter is wrapping those lines (because it sees them as plain text, not code), but that ends up with a C# string that is split over two lines, which is invalid.

ie, you have something like:

```
var class = "< really long list of css class names>";
```

and VS Code is formatting that into:

```
var class = "< first half of really long class names>
	<second half of really long class names>";
```

The C# errors about unterminated string literals cause us to abandon attempts to format the document. The fix here is probably to change the setting in VS Code for Html line length, but if you can't do that, or just don't want to, you should be able to get away with making those long strings verbatim strings (ie, change to `var class = @"<really long list>";`) so when VS Code wraps them, C# won't mind. There is one other place in this file where you have a ternary with long strings, and that needs to be changed to a proper if statement to avoid the issue.

Sadly we do not surface _any_ of this information to you, and its only by attaching a debugger to the Razor process, and formatting your actual .razor file, was I able to work it out. That is not a good experience, but I'm not sure how we can make it better.

**Comment by garrettlondon1** [comment]
Disabling the line wrap length to 0 fixes the formatting, I also got rid of some of the extra comments, etc. I don't think I want to disable wrapping permanently though. I can manually format that document, or maybe it's motivation to move stuff to the code behind :).
