### ISSUE TITLE
Code fixes often don't work (codeAction/resolve failed)

### ISSUE THREAD

**Issue by AlexanderInova** [dotnet/vscode-csharp#6700]
Type: <b>Bug</b>

## Issue Description ##
I am running VSCode on Linux within a devcontainer. 
The suggested C# code fixes often cannot be applied. It often states "Request codeAction/resolve failed.". 

I currently have no idea when and why. If I restart VSCode after the issue appeared, the exact same code-fix works as expected.

(This issue template recommends enabling "dotnet.server.trace", so I will do so and update this issue once there is more information.)

## Steps to Reproduce ##
In my current case: 
1. Open a .cs class file within a subdirectory of a project. 
2. Ensure the folder structure does not match the namespace of that class (which, in my case, is by default when creating the class using this C# extension within the Solution Explorer). 
3. Try to apply the code fix "Change namespace to '{0}'". 

## Expected Behavior ##
The namespace is changed according to the folder structure and probably the project settings. 

## Actual Behavior ##
An error pops up "Request codeAction/resolve failed." 
The C# log outputs "The solution does not contain the specified document." - which is not true.

### C# log ###
<details>
[Error - 11:20:47 AM] [LanguageServerHost] System.InvalidOperationException: The solution does not contain the specified document.
   at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution, DocumentId documentId) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ISolutionExtensions.cs:line 48
   at Microsoft.CodeAnalysis.ChangeNamespace.AbstractChangeNamespaceService`3.<>c__DisplayClass26_0.<ChangeNamespaceInSingleDocumentAsync>b__4(IGrouping`2 refInOneDocument) in /_/src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractChangeNamespaceService.cs:line 477
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll[TResult](IEnumerable`1 tasks)
   at Microsoft.CodeAnalysis.ChangeNamespace.AbstractChangeNamespaceService`3.ChangeNamespaceInSingleDocumentAsync(Solution solution, DocumentId id, String oldNamespace, String newNamespace, CodeCleanupOptionsProvider fallbackOptions, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractChangeNamespaceService.cs:line 475
   at Microsoft.CodeAnalysis.ChangeNamespace.AbstractChangeNamespaceService`3.ChangeNamespaceAsync(Document document, SyntaxNode container, String targetNamespace, CodeCleanupOptionsProvider fallbackOptions, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractChangeNamespaceService.cs:line 225
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 285
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(Solution originalSolution, IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 222
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActionResolveHandler.HandleRequestAsync(CodeAction codeAction, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHandler.cs:line 94
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
[Error - 11:20:47 AM] Request codeAction/resolve failed.
  Message: The solution does not contain the specified document.
  Code: -32000 
[object Object]
</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.84.2
**C# Extension**: 2.10.28
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     debian
 OS Version:  12
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|angular-console|nrwl|18.10.1|nrwl.angular-console-18.10.1|
|code-spell-checker|streetsidesoftware|3.0.1|streetsidesoftware.code-spell-checker-3.0.1|
|copilot|GitHub|1.139.0|github.copilot-1.139.0|
|copilot-chat|GitHub|0.10.2|github.copilot-chat-0.10.2|
|csdevkit|ms-dotnettools|1.0.14|ms-dotnettools.csdevkit-1.0.14-linux-x64|
|csharp|ms-dotnettools|2.10.28|ms-dotnettools.csharp-2.10.28-linux-x64|
|ilspy-vscode|icsharpcode|0.17.0|icsharpcode.ilspy-vscode-0.17.0|
|markdown-all-in-one|yzhang|3.5.1|yzhang.markdown-all-in-one-3.5.1|
|nugetpackagemanagergui|aliasadidev|2.0.6|aliasadidev.nugetpackagemanagergui-2.0.6|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|vscode-docker|ms-azuretools|1.28.0|ms-azuretools.vscode-docker-1.28.0|
|vscode-dotnet-runtime|ms-dotnettools|2.0.0|ms-dotnettools.vscode-dotnet-runtime-2.0.0|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-nuget-gallery|patcx|0.0.24|patcx.vscode-nuget-gallery-0.0.24|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-linux-x64|;

</details>

Extension version: 2.12.19
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.2.0-37-generic snap
Modes:
Remote OS version: Linux x64 6.2.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 3820)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.52GB (48.24GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|Dev Container: C# (.NET)|
|OS|Linux x64 6.2.0-37-generic|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 3564)|
|Memory (System)|62.52GB (48.24GB free)|
|VM|0%|
</details>

**Comment by jasonmalinowski** [comment]
This might already be fixed with https://github.com/dotnet/roslyn/pull/70669; not sure if @Cosifne might want to look at this. 

@AlexanderInova do you have a source generator running in this project? If you upgrade to 2.12.19 (which just released yesterday) is it fixed?

**Comment by AlexanderInova** [comment]
I configured "dotnet.server.trace" and then restarted VS Code, which seemed to automatically update the extension (at least it is now on 2.12.19). The last few ours the issue didn't appear. If the issue doesn't appear tomorrow, I'll let you know here and close the issue assuming you were right. Thank you so far.

**Comment by AlexanderInova** [comment]
The issue didn't appear again since the new update was installed. This might indicate that you were right and it is probably already fixed with https://github.com/dotnet/roslyn/pull/70669. 

So it was fixed even before I actually reported it - that's quite fast. :)

Thank you very much!

**Comment by jasonmalinowski** [comment]
> So it was fixed even before I actually reported it - that's quite fast. :)

Our time machine is still in the shop, so in this case you just got lucky and we had other reports too. :smile:
