### ISSUE TITLE
C# Intellisense isn't working in VSCode due to missing fallback folder

### ISSUE THREAD

**Issue by fmotion1** [dotnet/vscode-csharp#6701]
## Environment data
`dotnet --info` output:

```
11-30 13:27:04 C:\Users\futur\Desktop> dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.8d38d0cc
 [maui-windows]
   Installation Source: VS 17.8.34322.80
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34322.80
   Manifest Version:    17.0.8478/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.0.8478\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34322.80
   Manifest Version:    17.0.8478/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.0.8478\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34322.80
   Manifest Version:    34.0.43/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.417 [C:\Program Files\dotnet\sdk]
  7.0.404 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

VS Code version: 
```
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

C# Extension version: `v2.12.19`

## OmniSharp log

```
Starting OmniSharp server at 11/30/2023, 1:23:11 PM
    Target: d:\Dev\CSharp\Repos\00 Old\MetadataExtractorTemp\MetadataExtractorTemp.sln

OmniSharp server started with .NET 8.0.100
.
    Path: c:\Users\futur\.vscode\extensions\ms-dotnettools.csharp-2.12.19-win32-x64\.omnisharp\1.39.10-net6.0\OmniSharp.dll
    PID: 28288

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.19045.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: .NET Core SDK 8.0.100 17.8.3 - "C:\Program Files\dotnet\sdk\8.0.100\"
            2: .NET Core SDK 7.0.404 17.7.4 - "C:\Program Files\dotnet\sdk\7.0.404\"
            3: .NET Core SDK 6.0.417 17.3.2 - "C:\Program Files\dotnet\sdk\6.0.417\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 8.0.100 17.8.3 - "C:\Program Files\dotnet\sdk\8.0.100\"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Dev\CSharp\Repos\00 Old\MetadataExtractorTemp\'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'd:\Dev\CSharp\Repos\00 Old\MetadataExtractorTemp\MetadataExtractorTemp.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Dev\CSharp\Repos\00 Old\MetadataExtractorTemp\MetadataExtractorTemp\MetadataExtractorTemp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Dev\CSharp\Repos\00 Old\MetadataExtractorTemp\'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Dev\CSharp\Repos\00 Old\MetadataExtractorTemp\' on host 6472.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Dev\CSharp\Repos\00 Old\MetadataExtractorTemp\MetadataExtractorTemp\MetadataExtractorTemp.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "ResolvePackageAssets" task failed unexpectedly.
NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Program Files (x86)\Syncfusion\Essential Studio\WPF\20.2.0.36\ToolboxNuGetPackages'.
   at NuGet.Packaging.FallbackPackagePathResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders)
   at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(IEnumerable`1 packageFolders)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Dev\CSharp\Repos\00 Old\MetadataExtractorTemp\MetadataExtractorTemp\MetadataExtractorTemp.csproj'.
d:\Dev\CSharp\Repos\00 Old\MetadataExtractorTemp\MetadataExtractorTemp\MetadataExtractorTemp.csproj
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): Error: The "ResolvePackageAssets" task failed unexpectedly.
NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Program Files (x86)\Syncfusion\Essential Studio\WPF\20.2.0.36\ToolboxNuGetPackages'.
   at NuGet.Packaging.FallbackPackagePathResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders)
   at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(IEnumerable`1 packageFolders)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Dev\CSharp\Repos\00 Old\MetadataExtractorTemp\MetadataExtractorTemp\MetadataExtractorTemp.csproj
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 0.
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: d:\Dev\Powershell\VSYSModules\VSYSDevOps\Templates\csproj\ConsoleApp\Program.cs added to workspace
[warn]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 22,
  "Command": "/quickinfo",
  "Arguments": {
    "FileName": "d:\\Dev\\Powershell\\VSYSModules\\VSYSDevOps\\Templates\\csproj\\ConsoleApp\\Program.cs",
    "Line": 4,
    "Column": 16
  }
}
[fail]: OmniSharp.Stdio.Host
        ************  Response (6.2916ms) ************ 
{
  "Request_seq": 22,
  "Command": "/quickinfo",
  "Running": true,
  "Success": false,
  "Message": "\"System.ArgumentOutOfRangeException: The requested line number 4 must be less than the number of lines 3. (Parameter 'Line')\\r\\n   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position)\\r\\n   at OmniSharp.Extensions.SourceTextExtensions.GetTextPosition(SourceText sourceText, Request request) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn\\\\Extensions\\\\SourceTextExtensions.cs:line 11\\r\\n   at OmniSharp.Roslyn.CSharp.Services.QuickInfoProvider.Handle(QuickInfoRequest request) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\QuickInfoProvider.cs:line 61\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.GetFirstNotEmptyResponseFromHandlers(ExportHandler`2[] handlers, TRequest request) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 200\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.HandleRequestForLanguage(String language, TRequest request, RequestPacket packet) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 229\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.Process(RequestPacket packet, LanguageModel model, JToken requestObject) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 130\\r\\n   at OmniSharp.Stdio.Host.HandleRequest(String json, ILogger logger) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:line 218\"",
  "Body": null,
  "Seq": 52,
  "Type": "response"
}

```

## Steps to reproduce

1. Open or create a C# file.
2. Start typing `Console.` and notice there are absolutely no suggestions. Like `WriteLine`
3. Other commands don't produce Intellisense suggestions.

## Expected  behavior

Intellisense suggestions appear as I type my code.

## Actual behavior

No Intellisense suggestions appear as I type my code.

## Additional context

I did some research and some people are saying updating to the latest version helped. So I downloaded the [v2.12.19](https://github.com/dotnet/vscode-csharp/releases/tag/v2.12.19) release from here: https://github.com/dotnet/vscode-csharp/releases, but there is no VSIX in the source. I don't know how to proceed. I need Intellisense working.

Please, I beg you guys, help me! :(

Thanks,
Jay

**Comment by jasonmalinowski** [comment]
So I'm a bit confused: I see you have 2.12.19 installed which is indeed our latest release. We don't generally upload the VSIXes to the GitHub releases, you can just download them directly from the VS Code gallery: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp; the version history tab also lets you download them if you need them somewhere else.

Was this working in a prior version? You also have the flag to use omnisharp enabled given you're sharing an omnisharp log. Does it work if that's disabled and you're using the LSP engine?

I also see this in the log:

> NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Program Files (x86)\Syncfusion\Essential Studio\WPF\20.2.0.36\ToolboxNuGetPackages'.

Does that path actually exist? Did you uninstall something that removed it but might have left a pointer to the folder in place?

**Comment by jasonmalinowski** [comment]
@fmotion1 Are you able to share any more of the info to help us get to the bottom of this?
