### ISSUE TITLE
Not able to view CsWin32 generated code in VS Code

### ISSUE THREAD

**Issue by altamkp** [dotnet/vscode-csharp#6830]
## Is your feature request related to a problem? Please describe.
I have recently started using [CsWin32](https://github.com/microsoft/CsWin32) to generate Win32 APIs for my projects. The generated code can be opened in Visual Studio like below with "Go To Definition" .

![image](https://github.com/dotnet/vscode-csharp/assets/65537185/63008812-83b4-40fc-92f0-42dd40412d22)

But when trying to open in VS Code the following error is shown.

![image](https://github.com/dotnet/vscode-csharp/assets/65537185/6e989480-7ffe-4575-958e-ad5b6b0cfcc7)

```
2024-01-25 10:49:24.379 [error] Unable to resolve resource source-generated:/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.SourceGenerator/Windows.Win32.PInvoke.KERNEL32.dll.g.cs: Error: Unable to resolve resource source-generated:/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.SourceGenerator/Windows.Win32.PInvoke.KERNEL32.dll.g.cs
    at f.r (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2158:18772)
    at f.r (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2158:18758)
    at async y.acquire (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:37:3392)
    at async d.createModelReference (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2158:20107)
2024-01-25 10:49:24.889 [error] Error: Unable to resolve resource source-generated:/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.SourceGenerator/Windows.Win32.PInvoke.KERNEL32.dll.g.cs
    at f.r (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2158:18772)
    at f.r (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2158:18758)
    at async y.acquire (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:37:3392)
    at async d.createModelReference (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2158:20107)
    at async o.resolve (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1899:40832)
    at async r.setInput (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2148:11476)
    at async b.S (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2146:23046)
    at async b.L (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2146:21637)
    at async b.openEditor (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2146:20603)
    at async vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2275:23005
    at async v.M (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1184:80268)
    at async v.openCodeEditor (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:720:4538)
    at async N.m (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:765:56908)
    at async N.l (vscode-file://vscode-app/c:/Users/altamkp/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:765:56696)
```

Please see the issue I have filed in CsWin32, together with an MRE I have created.

[CsWin32 Github issue](https://github.com/microsoft/CsWin32/issues/1128)

[CsWin32Test.zip](https://github.com/dotnet/vscode-csharp/files/14045638/CsWin32Test.zip)

## Describe the solution you would like
It would be great if the generated code can be viewed in VS Code.

## Applicable Scenarios
View generated code from source generators.

## Describe alternatives you've considered
Using Visual Studio instead, but I pretty much prefer using VS Code.

**Comment by jasonmalinowski** [comment]
This is a known limitation we're currently working on fixing; we'll close https://github.com/dotnet/vscode-csharp/issues/6426 once this support is implemented.
