### ISSUE TITLE
Constant error messages appearing in bottom right

### ISSUE THREAD

**Issue by james-white-x** [dotnet/vscode-csharp#6837]
Type: <b>Bug</b>

## Issue Description ##
I constantly have C# Extension errors popping up as I develop with dotnet watch running.

Request textDocument/hover failed.
Request textDocument/semanticTokens/range failed.

## Steps to Reproduce ##
Run dotnet watch
Develop

## Expected Behavior ##
Not to show these error messages as they have zero relevance and do not affect anything in any way

## Actual Behavior ##
Annoying messages constantly popping up

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.85.2
**C# Extension**: 2.15.30
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|aspnetcorerazor-html-css-class-completion|kevin-chatham|1.0.3|kevin-chatham.aspnetcorerazor-html-css-class-completion-1.0.3|
|csharp|ms-dotnettools|2.15.30|ms-dotnettools.csharp-2.15.30-linux-x64|
|data-workspace-vscode|ms-mssql|0.5.0|ms-mssql.data-workspace-vscode-0.5.0|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|gitflow|vector-of-bool|1.2.1|vector-of-bool.gitflow-1.2.1|
|githistory|donjayamanne|0.6.20|donjayamanne.githistory-0.6.20|
|mssql|ms-mssql|1.22.1|ms-mssql.mssql-1.22.1|
|powershell|ms-vscode|2024.0.0|ms-vscode.powershell-2024.0.0|
|prettier-sql-vscode|inferrinizzard|1.6.0|inferrinizzard.prettier-sql-vscode-1.6.0|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|sql-bindings-vscode|ms-mssql|0.4.0|ms-mssql.sql-bindings-vscode-0.4.0|
|sql-database-projects-vscode|ms-mssql|1.4.1|ms-mssql.sql-database-projects-vscode-1.4.1|
|sqltools|mtxr|0.28.1|mtxr.sqltools-0.28.1|
|sqltools-driver-mssql|mtxr|0.4.2|mtxr.sqltools-driver-mssql-0.4.2|
|svg|jock|1.5.3|jock.svg-1.5.3|
|todo-tree|Gruntfuggly|0.0.226|gruntfuggly.todo-tree-0.0.226|
|vscode-color-picker|AntiAntiSepticeye|0.0.4|antiantisepticeye.vscode-color-picker-0.0.4|
|vscode-dotnet-pack|ms-dotnettools|1.0.13|ms-dotnettools.vscode-dotnet-pack-1.0.13|
|vscode-dotnet-runtime|ms-dotnettools|2.0.1|ms-dotnettools.vscode-dotnet-runtime-2.0.1|
|vscode-eslint|dbaeumer|2.4.4|dbaeumer.vscode-eslint-2.4.4|
|vscode-html-css|ecmel|2.0.7|ecmel.vscode-html-css-2.0.7|
|vscode-import-cost|wix|3.3.0|wix.vscode-import-cost-3.3.0|
|vscode-jest|Orta|5.2.3|orta.vscode-jest-5.2.3|
|vscode-lottie|lottiefiles|1.0.5|lottiefiles.vscode-lottie-1.0.5|
|vscode-markdownlint|DavidAnson|0.54.0|davidanson.vscode-markdownlint-0.54.0|
|vscode-nuget-gallery|patcx|0.0.24|patcx.vscode-nuget-gallery-0.0.24|
|vscode-pull-request-github|GitHub|0.78.1|github.vscode-pull-request-github-0.78.1|
|vscode-xml|redhat|0.26.1|redhat.vscode-xml-0.26.1-linux-x64|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|;

</details>

Extension version: 2.15.30
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 Microsoft Surface (R) Edition (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.45GB (1.23GB free)|
|Process Argv|--crash-reporter-id f28b5a18-e7d9-4c97-873a-6695beca75bd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 Microsoft Surface (R) Edition (8 x 1996)|
|Memory (System)|7.76GB (1.51GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30933248
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
3ef8e399:30949928

```

</details>

**Comment by james-white-x** [comment]
[csharp.log](https://github.com/dotnet/vscode-csharp/files/14095611/csharp.log)

Output log attached

**Comment by dibarbet** [comment]
Oof, lots of issues with text not matching
```
[Error - 11:13:32 AM] [LanguageServerHost] System.ArgumentOutOfRangeException: The requested line number 410 must be less than the number of lines 242. (Parameter 'Line')
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in /_/src/Compilers/Core/Portable/Text/TextLineCollection.cs:line 67
   at Microsoft.CodeAnalysis.LanguageServer.Extensions.GetPositionFromLinePositionAsync(TextDocument document, LinePosition linePosition, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Extensions/Extensions.cs:line 171
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CompletionHandler.HandleRequestAsync(CompletionParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs:line 55
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
```

These errors mean that hover and semantic tokens are not working.

@james-white-x is this by chance a razor file?  We've had similar issues there before.

**Comment by ptasznikarium** [comment]
I have exactly same issue on two separate machines.
Constant spam of "Request textDocument/semanticTokens/range failed." when working on .razor files.

**Comment by dibarbet** [comment]
Moving this over to the Razor side to look.
