### ISSUE TITLE
System.Private.Interop is not digitally signed

### ISSUE THREAD

**Issue by scoizzle** [dotnet/vscode-csharp#6839]
Type: <b>Bug</b>

## Issue Description ##
System.Private.Interop.dll included in .debugger as part of the C# extension is not distributed as signed and prevents me from debugging via vscode in my environment.

## Steps to Reproduce ##
1. Open any C# project in VS Code
2. Generate Build and Debug assets
3. Begin Debugging
4. My environment prevents the assembly from being loaded as it is not signed.
## Expected Behavior ##
Debugging session would begin as expected.

## Actual Behavior ##
Error in Debug console:
Internal error in the debugger.
Exception = System.Runtime.InteropServices.COMException
Message = Internal error in the debugger.
Code = 80004005
   at VsDbg.NativeEntryPoint.StartSession(String[] argv, InputCallback pfnInputCallback, OutputCallback pfnOutputCallback)
   at VsDbg.Transports.LocalTransport.<Init>b__28_0()

### C# log ###
<details>
Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\1f60fb2d"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 3:32:04 PM] [Program] Language server initialized
[Info  - 3:32:29 PM] [WorkspaceProjectFactoryService] Project [Redacted] loaded by C# Dev Kit
[Info  - 3:32:29 PM] [WorkspaceProjectFactoryService] Project [Redacted] loaded by C# Dev Kit
Using dotnet configured on PATH
</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.85.2
**C# Extension**: 2.15.30
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
 [wasm-tools-net6]
   Installation Source: VS 17.7.34024.191
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net6\8.0.1\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: VS 17.7.34024.191
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.1\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.417 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.6|ms-vscode.azure-account-0.11.6|
|azurerm-vscode-tools|msazurermtools|0.15.11|msazurermtools.azurerm-vscode-tools-0.15.11|
|blazorwasm-companion|ms-dotnettools|1.1.4|ms-dotnettools.blazorwasm-companion-1.1.4|
|csdevkit|ms-dotnettools|1.2.7|ms-dotnettools.csdevkit-1.2.7-win32-x64|
|csharp|ms-dotnettools|2.15.30|ms-dotnettools.csharp-2.15.30-win32-x64|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|file-downloader|mindaro-dev|1.0.13|mindaro-dev.file-downloader-1.0.13|
|gitlens|eamodio|14.7.0|eamodio.gitlens-14.7.0|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|js-debug-nightly|ms-vscode|2024.1.2217|ms-vscode.js-debug-nightly-2024.1.2217|
|live-server|ms-vscode|0.4.13|ms-vscode.live-server-0.4.13|
|nugetpackagemanagergui|aliasadidev|2.0.6|aliasadidev.nugetpackagemanagergui-2.0.6|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|rainbow-csv|mechatroner|3.11.0|mechatroner.rainbow-csv-3.11.0|
|remote-containers|ms-vscode-remote|0.327.0|ms-vscode-remote.remote-containers-0.327.0|
|remote-explorer|ms-vscode|0.4.1|ms-vscode.remote-explorer-0.4.1|
|remote-server|ms-vscode|1.5.0|ms-vscode.remote-server-1.5.0|
|remote-ssh|ms-vscode-remote|0.107.1|ms-vscode-remote.remote-ssh-0.107.1|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|remote-wsl|ms-vscode-remote|0.81.9|ms-vscode-remote.remote-wsl-0.81.9|
|vscode-azureresourcegroups|ms-azuretools|0.8.3|ms-azuretools.vscode-azureresourcegroups-0.8.3|
|vscode-azurestaticwebapps|ms-azuretools|0.12.2|ms-azuretools.vscode-azurestaticwebapps-0.12.2|
|vscode-dotnet-runtime|ms-dotnettools|2.0.1|ms-dotnettools.vscode-dotnet-runtime-2.0.1|
|vscode-eslint|dbaeumer|2.4.4|dbaeumer.vscode-eslint-2.4.4|
|vscode-remote-extensionpack|ms-vscode-remote|0.25.0|ms-vscode-remote.vscode-remote-extensionpack-0.25.0|
|vscode-sprint-planner|ipatalas|0.6.2|ipatalas.vscode-sprint-planner-0.6.2|
|vscode-sql-formatter|adpyke|1.4.4|adpyke.vscode-sql-formatter-1.4.4|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|
|vsliveshare|ms-vsliveshare|1.0.5905|ms-vsliveshare.vsliveshare-1.0.5905|;

</details>

Extension version: 2.15.30
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.77GB free)|
|Process Argv|--crash-reporter-id 87abacd1-fdc8-442b-8b36-a5357115dcee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30951918
3ef8e399:30949928

```

</details>

**Comment by gregg-miskelly** [comment]
Opps! Not sure how that managed to sneak through the cracks, but thanks for letting us know.

**Comment by scoizzle** [comment]
Thanks Greg! Can't wait to be productive again 😂
