### ISSUE TITLE
Microsoft.CodeAnalysis.LanguageServer server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by mikekistler** [dotnet/vscode-csharp#7630]
Type: <b>Bug</b>

The C# extension (I think) crashes with this message when I open a Polyglot notebook inside a devcontainer for .NET 9:
> The Microsoft.CodeAnalysis.LanguageServer server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

I did look at #5964 but at end of this is a request to open new issues if the problem recurs, so I'm doing that.

I've captured the full log and will post it once the issue is open.

Extension version: 2.45.25
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 24.0.0
Modes:
Remote OS version: Linux arm64 6.10.4-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 6|
|Memory (System)|32.00GB (1.31GB free)|
|Process Argv|. --crash-reporter-id 419d896f-7e85-4c21-8845-5a77abdaec9d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: C# (.NET) @ desktop-linux|
|OS|Linux arm64 6.10.4-linuxkit|
|CPUs|unknown (10 x 0)|
|Memory (System)|7.66GB (4.40GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31150322
notype1:31151523
cc771715:31146322

```

</details>

**Comment by mikekistler** [comment]
Full log is attached.

[log.txt](https://github.com/user-attachments/files/17259817/log.txt)

**Comment by dibarbet** [comment]
@mikekistler would you mind also posting the 'C# LSP Trace log' output window contents?  Looks like we're getting an invalid URI and the C# LSP trace logs should help figure out what is creating it.  You can see instructions for enabling the trace log here - https://github.com/dotnet/vscode-csharp/blob/main/SUPPORT.md#collecting-general-logs
```
[Error - 2:02:49 PM] [LanguageServerHost] System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)

```

**Comment by mikekistler** [comment]
Here's the new log. One observation is that it seems that I need to have the Polyglot notebooks extension installed in order to repro.

[log2.txt](https://github.com/user-attachments/files/17307114/log2.txt)

**Comment by mikekistler** [comment]
This is still happening for me, and quite frequently. Is there any additional debug information I can provide?

**Comment by dibarbet** [comment]
@mikekistler apologies for the delay - it looks like you attached the `C#` output window logs, but in this case I'll need to look at the logs from the `C# LSP Trace Logs` output window, if you wouldn't mind collecting those.

Thanks!

**Comment by mikekistler** [comment]
Okay ... just had this occur again and attempted to collect the C# LSP Trace Logs but found they are empty:

![Image](https://github.com/user-attachments/assets/83b51da4-8bac-482d-8eea-20471e034000)

However, I think I can give more details on a recreate scenario now. What I did to cause this failure was attempt to open a polyglot notebook file when running VSCode in a dev container with both .NET 8 and .NET 9 SDKs installed.

After opening in the container, .cs files open file and C#/DevKit is working. Then I open a polyglot notebook (.ipynb) and that cause the failure. From that point on C#/DevKit is dead and I have to rebuild the container to get it back to functional again.

I think I can probably recreate this at will so if there is any other debugging information you need to help debug this just let me know. Or if you want to do a live debug session I'm also happy to make time for that.

**Comment by dibarbet** [comment]
@mikekistler if you could try using the latest C# extension version (2.55.29 or higher) - we modified how the trace logs are collected.
See https://github.com/dotnet/vscode-csharp/blob/main/SUPPORT.md#c-lsp-trace-logs - basically in the `C#` output window use the gear to set the level to `Trace` - then open the `C# LSP Trace Logs` output window and reproduce the issue.  

Can attach the full contents of the `C# LSP Trace Logs` window here

**Comment by dibarbet** [comment]
If you can share a repo+devcontainer that reproduces it consistently, that would also be extremely helpful.  My microsoft email is listed on my github profile if you'd prefer to share that way.

**Comment by dibarbet** [comment]
> Sent a repo link and more info in email.

Got the mail - was OOF for a couple weeks, but will take a look at this next week.

**Comment by dibarbet** [comment]
This is caused by https://github.com/dotnet/runtime/issues/64707

The URI we're getting passed by VSCode for the C# part of the notebook file is something like
```
vscode-notebook-cell://dev-container+7b2/workspaces/devkit-crash/notebook.ipynb
```

and System.Uri barfs on the `+` in the host name.

**Comment by dibarbet** [comment]
Assigning to myself - need to take a spike of what it would take to remove `System.Uri` entirely from the LSP serialization as it causes us plenty of issues.

**Comment by dibarbet** [comment]
Using https://github.com/dotnet/vscode-csharp/issues/7638 to track instead - closing this as a dupe
