### ISSUE TITLE
Intelisense doesn't work in Devcontainer

### ISSUE THREAD

**Issue by Jarzab3kDH** [dotnet/vscode-csharp#7818]
## Issue Description ##

While working on C# code suddenly Intelisense stops working, when I try to restart Language Server I see following errors in Logs:

 [stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/dh207665/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/dh207665/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools

2024-11-22 08:19:33.393 [info] [stdout] {"pipeName":"/tmp/a5d05b99.sock"}

2024-11-22 08:19:33.393 [info] received named pipe information from server
2024-11-22 08:19:33.393 [info] client has connected to server
2024-11-22 08:19:33.456 [info] [Info  - 8:19:33 AM] [Program] Language server initialized
2024-11-22 08:21:28.297 [info] Using dotnet configured on PATH

It says server is initialized but actually any changes to the source code are not affecting UI, for example after fixing compile error, the old error will be shown in UI.

## Expected Behavior ##

Intelisense works without sudden breaks.

## Actual Behavior ##

Intelisense works for some time, restart of Language server doesn't help, only reloading window helps.

### C# log ###
<details>2024-11-22 08:37:24.145 [info] Using dotnet configured on PATH
2024-11-22 08:37:24.147 [info] Dotnet path: /usr/share/dotnet/dotnet
2024-11-22 08:37:24.147 [info] Activating C# + C# Dev Kit...
2024-11-22 08:37:26.312 [info] [stdout] {"pipeName":"/tmp/545b2d16.sock"}

2024-11-22 08:37:26.312 [info] received named pipe information from server
2024-11-22 08:37:26.312 [info] client has connected to server
2024-11-22 08:37:26.414 [info] [Info  - 8:37:26 AM] [Program] Language server initialized
2024-11-22 08:37:30.823 [info] [Info  - 8:37:30 AM] [WorkspaceProjectFactoryService] Project /workspaces/domain-reference-app/tests/dd.DomainReferenceApp.Pacts/dd.DomainReferenceApp.Pacts.csproj loaded by C# Dev Kit
2024-11-22 08:37:30.875 [info] [Info  - 8:37:30 AM] [WorkspaceProjectFactoryService] Project /workspaces/domain-reference-app/tests/dd.DomainReferenceApp.IntegrationTests/dd.DomainReferenceApp.IntegrationTests.csproj loaded by C# Dev Kit
2024-11-22 08:37:30.914 [info] [Info  - 8:37:30 AM] [WorkspaceProjectFactoryService] Project /workspaces/domain-reference-app/src/dd.DomainReferenceApp.Api/dd.DomainReferenceApp.Api.csproj loaded by C# Dev Kit
2024-11-22 08:37:33.482 [info] [Error - 8:37:33 AM] [LanguageServerHost] StreamJsonRpc.LocalRpcException: Resolve version '2024-11-22T08:37:32.8413958Z-10033-0' does not match current version '2024-11-22T08:37:33.2435643Z-10060-0'
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeLens.CodeLensResolveHandler.HandleRequestAsync(CodeLens request, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs:line 55
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
2024-11-22 08:37:33.482 [info] [Error - 8:37:33 AM] [LanguageServerHost] StreamJsonRpc.LocalRpcException: Resolve version '2024-11-22T08:37:32.8413958Z-10033-0' does not match current version '2024-11-22T08:37:33.2435643Z-10060-0'
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeLens.CodeLensResolveHandler.HandleRequestAsync(CodeLens request, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs:line 55
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
2024-11-22 08:37:33.482 [info] [Error - 8:37:33 AM] [LanguageServerHost] StreamJsonRpc.LocalRpcException: Resolve version '2024-11-22T08:37:32.8413958Z-10033-0' does not match current version '2024-11-22T08:37:33.2435643Z-10060-0'
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeLens.CodeLensResolveHandler.HandleRequestAsync(CodeLens request, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs:line 55
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
2024-11-22 08:37:33.482 [info] [Error - 8:37:33 AM] [LanguageServerHost] StreamJsonRpc.LocalRpcException: Resolve version '2024-11-22T08:37:32.8413958Z-10033-0' does not match current version '2024-11-22T08:37:33.2435643Z-10060-0'
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeLens.CodeLensResolveHandler.HandleRequestAsync(CodeLens request, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs:line 55
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 191
2024-11-22 08:38:04.435 [info] [Info  - 8:38:04 AM] [WorkspaceProjectFactoryService] Project /workspaces/domain-reference-app/src/dd.DomainReferenceApp.Domain/dd.DomainReferenceApp.Domain.csproj loaded by C# Dev Kit
2024-11-22 08:38:04.513 [info] [Info  - 8:38:04 AM] [WorkspaceProjectFactoryService] Project /workspaces/domain-reference-app/src/dd.DomainReferenceApp.Infrastructure/dd.DomainReferenceApp.Infrastructure.csproj loaded by C# Dev Kit
2024-11-22 08:38:04.523 [info] [Info  - 8:38:04 AM] [WorkspaceProjectFactoryService] Project /workspaces/domain-reference-app/tests/dd.DomainReferenceApp.Api.UnitTests/dd.DomainReferenceApp.Api.UnitTests.csproj loaded by C# Dev Kit
2024-11-22 08:38:04.605 [info] [Info  - 8:38:04 AM] [WorkspaceProjectFactoryService] Project /workspaces/domain-reference-app/src/dd.DomainReferenceApp.Stub/dd.DomainReferenceApp.Stub.csproj loaded by C# Dev Kit
2024-11-22 08:39:00.451 [info] [Info  - 8:39:00 AM] Shutting down
2024-11-22 08:39:00.643 [info] Using dotnet configured on PATH
2024-11-22 08:39:00.644 [info] Dotnet path: /usr/share/dotnet/dotnet
2024-11-22 08:39:00.644 [info] Activating C# + C# Dev Kit...
2024-11-22 08:39:00.808 [info] [stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools
fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools

2024-11-22 08:39:02.449 [info] [stdout] {"pipeName":"/tmp/8c39a833.sock"}

2024-11-22 08:39:02.450 [info] received named pipe information from server
2024-11-22 08:39:02.450 [info] client has connected to server
2024-11-22 08:39:02.516 [info] [Info  - 8:39:02 AM] [Program] Language server initialized
2024-11-22 08:40:55.631 [info] [Info  - 8:40:55 AM] Shutting down
2024-11-22 08:40:55.833 [info] Using dotnet configured on PATH
2024-11-22 08:40:55.834 [info] Dotnet path: /usr/share/dotnet/dotnet
2024-11-22 08:40:55.834 [info] Activating C# + C# Dev Kit...
2024-11-22 08:40:55.974 [info] [stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools
fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools
fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools
fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools

2024-11-22 08:40:57.278 [info] [stdout] {"pipeName":"/tmp/b21c0639.sock"}

2024-11-22 08:40:57.278 [info] received named pipe information from server
2024-11-22 08:40:57.279 [info] client has connected to server
2024-11-22 08:40:57.344 [info] [Info  - 8:40:57 AM] [Program] Language server initialized
2024-11-22 08:44:18.980 [info] [Info  - 8:44:18 AM] Shutting down
2024-11-22 08:44:19.227 [info] Using dotnet configured on PATH
2024-11-22 08:44:19.228 [info] Dotnet path: /usr/share/dotnet/dotnet
2024-11-22 08:44:19.228 [info] Activating C# + C# Dev Kit...
2024-11-22 08:44:19.426 [info] [stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools
fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools
fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools
fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools
fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools
fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/user/.vscode-server/extensions/ms-dotnettools.csharp-2.55.29-linux-x64/.xamlTools

2024-11-22 08:44:20.941 [info] [stdout] {"pipeName":"/tmp/67b988ea.sock"}

2024-11-22 08:44:20.941 [info] received named pipe information from server
2024-11-22 08:44:20.941 [info] client has connected to server
2024-11-22 08:44:21.022 [info] [Info  - 8:44:21 AM] [Program] Language server initialized
</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires the `C#` output window log level to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.95.3
**C# Extension**: 2.55.29
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.18f19b92
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     debian
 OS Version:  12
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.403/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  8.0.403 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|code-spell-checker|streetsidesoftware|4.0.21|streetsidesoftware.code-spell-checker-4.0.21|
|copilot|GitHub|1.245.0|github.copilot-1.245.0|
|copilot-chat|GitHub|0.22.4|github.copilot-chat-0.22.4|
|csdevkit|ms-dotnettools|1.13.9|ms-dotnettools.csdevkit-1.13.9-linux-x64|
|csharp|ms-dotnettools|2.55.29|ms-dotnettools.csharp-2.55.29-linux-x64|
|vscode-docker|ms-azuretools|1.29.3|ms-azuretools.vscode-docker-1.29.3|
|vscode-dotnet-runtime|ms-dotnettools|2.2.3|ms-dotnettools.vscode-dotnet-runtime-2.2.3|
|vscode-eslint|dbaeumer|3.0.10|dbaeumer.vscode-eslint-3.0.10|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.18|ms-kubernetes-tools.vscode-kubernetes-tools-1.3.18|
|vscode-yaml|redhat|1.15.0|redhat.vscode-yaml-1.15.0|;

</details>

**Comment by Jarzab3kDH** [comment]
I wanted to add LSP Trace logs, but I only see `Razor > Server: Trace` option

**Comment by dibarbet** [comment]
Apologies for the delay here - @Jarzab3kDH we moved the C# trace log setting to the output window itself, see https://github.com/dotnet/vscode-csharp/blob/main/SUPPORT.md#collecting-general-logs

If you wouldn't mind collecting the trace logs that would be helpful.  Additionally any information about your dev container that you can provide?

**Comment by dibarbet** [comment]
closing, not enough info
